/**
 * CronExpressionGenerator 长文正文 —— 工具说明(英文;SSR 恒英文,与全站一致)
 */

export function CronExpressionGeneratorContent() {
  return (
    <section className="prose-content mt-10 max-w-3xl">
      <h2>Reading the five fields</h2>
      <p>Minute hour day-of-month month day-of-week, each accepting *, lists, ranges, and */N steps. The description line beneath the expression is generated by our own cron engine, so what you read is what schedulers will do.</p>
      <h2>Common gotchas</h2>
      <p>Day-of-month and day-of-week combine with OR when both are restricted (standard Vixie behavior) — a rule people trip over constantly. Also: cron has no timezone field; servers run UTC unless configured otherwise.</p>
      <h2>Presets vs custom</h2>
      <p>The presets cover 90% of real schedules: every N minutes, hourly at :MM, daily/weekdays/weekly at a fixed time. Anything more exotic belongs in a proper cron editor with validation — copy this output into one.</p>
    </section>
  )
}
