/**
 * SmartIcon —— 全站统一的工具图标渲染器(Lucide SVG,零 3D emoji)
 *
 * 职责:
 *  1. 把图标键(如 'calculator' / 'braces' / 'qr-code')映射为 lucide-react SVG;
 *  2. 兜底保护:旧的 emoji 图标(如 '⚙️')经 EMOJI_ICON_MAP 翻译成键,
 *     完全未知的字符串 → Wrench,保证界面上绝不泄漏任何原始 emoji;
 *  3. 数据侧的分辨逻辑(slug 优先 / category 兜底)仍在 lib/tools.ts 的
 *     getToolIcon(),本组件只做"键 → SVG"的最后一步渲染。
 *
 * 用法:
 *   <SmartIcon icon={getToolIcon(tool)} className="h-5 w-5" />
 */

import {
  ArrowDownAZ,
  ArrowLeftRight,
  Apple,
  Baby,
  BadgePercent,
  Banknote,
  BatteryCharging,
  Beaker,
  Binary,
  Box,
  Braces,
  Briefcase,
  Building2,
  Cake,
  Calculator,
  CalendarDays,
  CaseLower,
  CaseSensitive,
  CaseUpper,
  ChartColumn,
  Circle,
  CircleDollarSign,
  CircleDot,
  ClipboardList,
  Clock,
  Code,
  Coins,
  Contrast,
  CreditCard,
  Database,
  Dices,
  Diff,
  Divide,
  Droplets,
  Dumbbell,
  Eraser,
  FileCode,
  FileJson,
  FileText,
  Fingerprint,
  FlaskConical,
  Flame,
  Fuel,
  Gauge,
  Globe,
  GraduationCap,
  HardDrive,
  Hash,
  HeartPulse,
  Home,
  Image,
  KeyRound,
  Landmark,
  Layers,
  Link,
  List,
  ListOrdered,
  ListX,
  Lock,
  LockOpen,
  Mail,
  Minimize2,
  MoveHorizontal,
  Palette,
  Palmtree,
  PenLine,
  Percent,
  PersonStanding,
  PiggyBank,
  Puzzle,
  QrCode,
  Receipt,
  RectangleHorizontal,
  Repeat,
  Replace,
  Rocket,
  Ruler,
  Salad,
  Scale,
  Scissors,
  ScrollText,
  Search,
  Share2,
  Shield,
  ShieldCheck,
  ShoppingBag,
  Shuffle,
  Sigma,
  Sparkles,
  Tag,
  Target,
  Terminal,
  Thermometer,
  Timer,
  TrendingDown,
  TrendingUp,
  Triangle,
  Type,
  Unlink,
  Users,
  Wallet,
  Waves,
  Weight,
  WholeWord,
  WrapText,
  Wrench,
  Zap,
  type LucideIcon,
} from 'lucide-react'

/** 图标键 → Lucide 组件(全站唯一映射表) */
const ICON_MAP: Record<string, LucideIcon> = {
  calculator: Calculator,
  'credit-card': CreditCard,
  banknote: Banknote,
  home: Home,
  scale: Scale,
  briefcase: Briefcase,
  target: Target,
  'piggy-bank': PiggyBank,
  'scroll-text': ScrollText,
  'building-2': Building2,
  'circle-dollar-sign': CircleDollarSign,
  palmtree: Palmtree,
  repeat: Repeat,
  tag: Tag,
  landmark: Landmark,
  clock: Clock,
  rocket: Rocket,
  receipt: Receipt,
  wallet: Wallet,
  'shopping-bag': ShoppingBag,
  coins: Coins,
  'badge-percent': BadgePercent,
  percent: Percent,
  'person-standing': PersonStanding,
  salad: Salad,
  baby: Baby,
  apple: Apple,
  flame: Flame,
  droplets: Droplets,
  dumbbell: Dumbbell,
  users: Users,
  cake: Cake,
  'calendar-days': CalendarDays,
  'clipboard-list': ClipboardList,
  'graduation-cap': GraduationCap,
  box: Box,
  circle: Circle,
  'circle-dot': CircleDot,
  triangle: Triangle,
  'rectangle-horizontal': RectangleHorizontal,
  'trending-down': TrendingDown,
  'trending-up': TrendingUp,
  hash: Hash,
  puzzle: Puzzle,
  shuffle: Shuffle,
  dices: Dices,
  divide: Divide,
  sigma: Sigma,
  type: Type,
  binary: Binary,
  'flask-conical': FlaskConical,
  link: Link,
  scissors: Scissors,
  mail: Mail,
  globe: Globe,
  diff: Diff,
  'hard-drive': HardDrive,
  braces: Braces,
  'minimize-2': Minimize2,
  'arrow-left-right': ArrowLeftRight,
  'list-ordered': ListOrdered,
  list: List,
  palette: Palette,
  fingerprint: Fingerprint,
  'file-text': FileText,
  'shield-check': ShieldCheck,
  lock: Lock,
  'lock-open': LockOpen,
  code: Code,
  unlink: Unlink,
  'case-upper': CaseUpper,
  'case-lower': CaseLower,
  'case-sensitive': CaseSensitive,
  'pen-line': PenLine,
  'list-x': ListX,
  'arrow-down-a-z': ArrowDownAZ,
  'wrap-text': WrapText,
  replace: Replace,
  eraser: Eraser,
  'key-round': KeyRound,
  'whole-word': WholeWord,
  'qr-code': QrCode,
  weight: Weight,
  zap: Zap,
  timer: Timer,
  fuel: Fuel,
  gauge: Gauge,
  'battery-charging': BatteryCharging,
  waves: Waves,
  thermometer: Thermometer,
  beaker: Beaker,
  image: Image,
  'file-code': FileCode,
  terminal: Terminal,
  'share-2': Share2,
  layers: Layers,
  search: Search,
  sparkles: Sparkles,
  'move-horizontal': MoveHorizontal,
  contrast: Contrast,
  'file-json': FileJson,
  database: Database,
  wrench: Wrench,
  ruler: Ruler,
  'chart-column': ChartColumn,
  'heart-pulse': HeartPulse,
  shield: Shield,
}

/**
 * 旧 emoji 图标 → 图标键(兜底保护)。
 * 数据迁移完成后正常不会走到这里;只防御历史脏数据/未迁移调用点。
 * 未列出的 emoji → 最终兜底 'wrench'。
 */
const EMOJI_ICON_MAP: Record<string, string> = {
  '💳': 'credit-card',
  '🔤': 'type',
  '⚙️': 'code',
  '📐': 'ruler',
  '🧮': 'calculator',
  '❤️': 'heart-pulse',
  '⏰': 'clock',
  '🎓': 'graduation-cap',
  '🔒': 'lock',
  '🎨': 'palette',
  '💼': 'briefcase',
  '🛠️': 'wrench',
  '📈': 'trending-up',
  '💵': 'banknote',
  '🏠': 'home',
  '🏡': 'home',
  '🏦': 'landmark',
  '⚖️': 'scale',
  '🎯': 'target',
  '💰': 'piggy-bank',
  '📜': 'scroll-text',
  '📊': 'chart-column',
  '🏢': 'building-2',
  '🔄': 'repeat',
  '🏷️': 'tag',
  '🚀': 'rocket',
  '🧾': 'receipt',
  '💸': 'wallet',
  '🛍️': 'shopping-bag',
  '🪙': 'coins',
  '％': 'percent',
  '🥗': 'salad',
  '👶': 'baby',
  '🍎': 'apple',
  '🔥': 'flame',
  '💧': 'droplets',
  '🏋️': 'dumbbell',
  '👥': 'users',
  '🎂': 'cake',
  '📅': 'calendar-days',
  '📝': 'pen-line',
  '🧊': 'box',
  '⚽': 'circle',
  '🔺': 'triangle',
  '📉': 'trending-down',
  '🔢': 'hash',
  '🧩': 'puzzle',
  '🔀': 'shuffle',
  '🎲': 'dices',
  '🔬': 'flask-conical',
  '🔗': 'link',
  '✂️': 'scissors',
  '✉️': 'mail',
  '🌐': 'globe',
  '📑': 'diff',
  '💾': 'hard-drive',
  '📦': 'minimize-2',
  '📋': 'list',
  '🔑': 'key-round',
  '📄': 'file-text',
  '🛡️': 'shield-check',
  '🔐': 'lock',
  '🔓': 'lock-open',
  '🔠': 'case-upper',
  '🔡': 'case-lower',
  '🔍': 'search',
  '📱': 'qr-code',
  '⚡': 'zap',
  '🚰': 'droplets',
  '⏱️': 'timer',
  '⛽': 'fuel',
  '⏲️': 'gauge',
  '🔋': 'battery-charging',
  '📻': 'waves',
  '🌡️': 'thermometer',
  '📏': 'ruler',
  '🖼️': 'image',
  '🔷': 'braces',
  '🌀': 'terminal',
  '🌑': 'layers',
  '⭐': 'sparkles',
  '👁️': 'contrast',
  '🗄️': 'database',
}

/** 未知键/未映射 emoji 的最终兜底 */
const FALLBACK_ICON: LucideIcon = Wrench

export interface SmartIconProps {
  /** 图标键(如 'braces');兼容传入旧 emoji(自动翻译/兜底) */
  icon: string
  className?: string
}

export function SmartIcon({ icon, className = 'h-5 w-5' }: SmartIconProps) {
  const key = ICON_MAP[icon] ? icon : (EMOJI_ICON_MAP[icon] ?? undefined)
  const Icon = (key && ICON_MAP[key]) || FALLBACK_ICON
  return <Icon className={className} aria-hidden="true" strokeWidth={1.8} />
}
