/**
 * ⚠️ 本文件由 scripts/gen-related-index.mjs 自动生成,请勿手改。
 * 数据源:lib/tools.ts(发布工具的轻量四字段 + 推荐/下一步 slug 索引)。
 * registry 变更后重跑生成脚本(见脚本头注释)。
 *
 * 设计:客户端组件(RelatedTools / NextSteps)从这里取推荐数据,
 * 避免 import lib/tools.ts 把全量 SEO 注册表(~180KB min)拖进客户端
 * chunk。本模块仅含展示所需四字段,是「注册表 → 客户端」的瘦身投影。
 */

/** 轻量工具元数据:客户端展示所需的最小字段集 */
export interface ToolLiteMeta {
  slug: string
  name: string
  shortIntro: string
  category: string
}

/** slug → 轻量元数据(全部已上线工具) */
export const toolLiteMeta: Record<string, ToolLiteMeta> = {
  'loan-calculator': { slug: 'loan-calculator', name: 'Loan Calculator', shortIntro: 'Calculate monthly payments, total interest, and full cost of any loan.', category: 'Finance Calculators' },
  'mortgage-calculator': { slug: 'mortgage-calculator', name: 'Mortgage Calculator', shortIntro: 'Calculate monthly mortgage payments and total interest.', category: 'Finance Calculators' },
  'compound-interest-calculator': { slug: 'compound-interest-calculator', name: 'Compound Interest Calculator', shortIntro: 'See how your savings grow with the power of compound interest.', category: 'Finance Calculators' },
  'apy-calculator': { slug: 'apy-calculator', name: 'APY Calculator', shortIntro: 'Convert APR to APY accounting for compounding frequency.', category: 'Finance Calculators' },
  'roi-calculator': { slug: 'roi-calculator', name: 'ROI Calculator', shortIntro: 'Calculate total and annualized return on investment.', category: 'Finance Calculators' },
  'credit-card-minimum-payment-calculator': { slug: 'credit-card-minimum-payment-calculator', name: 'Credit Card Minimum Payment Calculator', shortIntro: 'See how your minimum payment splits between interest and principal.', category: 'Finance Calculators' },
  'cash-back-calculator': { slug: 'cash-back-calculator', name: 'Cash Back Calculator', shortIntro: 'Calculate true value of cash back rewards after annual fees.', category: 'Finance Calculators' },
  'down-payment-calculator': { slug: 'down-payment-calculator', name: 'Down Payment Calculator', shortIntro: 'Find your down payment amount and PMI status.', category: 'Finance Calculators' },
  'dti-calculator': { slug: 'dti-calculator', name: 'Debt-to-Income Calculator', shortIntro: 'Calculate DTI ratio and see if lenders will approve you.', category: 'Finance Calculators' },
  'commission-calculator': { slug: 'commission-calculator', name: 'Commission Calculator', shortIntro: 'Calculate sales commission plus base salary.', category: 'Finance Calculators' },
  'bill-split-calculator': { slug: 'bill-split-calculator', name: 'Bill Split Calculator', shortIntro: 'Split a bill evenly including tip.', category: 'Finance Calculators' },
  'savings-goal-calculator': { slug: 'savings-goal-calculator', name: 'Savings Goal Calculator', shortIntro: 'Find the monthly amount needed to reach any savings goal.', category: 'Finance Calculators' },
  'net-worth-calculator': { slug: 'net-worth-calculator', name: 'Net Worth Calculator', shortIntro: 'Calculate your net worth — assets minus liabilities.', category: 'Finance Calculators' },
  'annuity-calculator': { slug: 'annuity-calculator', name: 'Annuity Calculator', shortIntro: 'Find annual and monthly payouts from a principal over N years.', category: 'Finance Calculators' },
  'capital-gains-tax-estimator': { slug: 'capital-gains-tax-estimator', name: 'Capital Gains Tax Estimator', shortIntro: 'Estimate capital gains tax on investments (short vs long-term rates).', category: 'Finance Calculators' },
  'rent-vs-buy-calculator': { slug: 'rent-vs-buy-calculator', name: 'Rent vs Buy Calculator', shortIntro: 'Compare total cost of buying vs renting over a time period.', category: 'Finance Calculators' },
  'inflation-calculator': { slug: 'inflation-calculator', name: 'Inflation Calculator', shortIntro: 'See how inflation reduces the value of money over time.', category: 'Finance Calculators' },
  'retirement-calculator': { slug: 'retirement-calculator', name: 'Retirement Calculator', shortIntro: 'Project your retirement savings with compound growth.', category: 'Finance Calculators' },
  'simple-interest-calculator': { slug: 'simple-interest-calculator', name: 'Simple Interest Calculator', shortIntro: 'Calculate simple interest with the I = Prt formula.', category: 'Finance Calculators' },
  'unit-price-calculator': { slug: 'unit-price-calculator', name: 'Unit Price Calculator', shortIntro: 'Compare unit prices to find the real best deal.', category: 'Finance Calculators' },
  'markup-calculator': { slug: 'markup-calculator', name: 'Markup Calculator', shortIntro: 'Find selling price and margin from cost and markup.', category: 'Finance Calculators' },
  'hourly-to-salary-calculator': { slug: 'hourly-to-salary-calculator', name: 'Hourly to Salary Calculator', shortIntro: 'Convert your hourly wage to annual salary.', category: 'Finance Calculators' },
  'credit-card-payoff-calculator': { slug: 'credit-card-payoff-calculator', name: 'Credit Card Payoff Calculator', shortIntro: 'See how long to pay off your credit card balance.', category: 'Finance Calculators' },
  'income-tax-estimator': { slug: 'income-tax-estimator', name: 'Income Tax Estimator', shortIntro: 'Estimate US federal income tax and take-home pay.', category: 'Finance Calculators' },
  'salary-converter': { slug: 'salary-converter', name: 'Salary Converter', shortIntro: 'Convert salary between annual, monthly, bi-weekly, and hourly.', category: 'Finance Calculators' },
  'sales-tax-calculator': { slug: 'sales-tax-calculator', name: 'Sales Tax Calculator', shortIntro: 'Add or remove sales tax from any price instantly.', category: 'Finance Calculators' },
  'tip-calculator': { slug: 'tip-calculator', name: 'Tip Calculator', shortIntro: 'Calculate tips and split bills fairly among any number of people.', category: 'Finance Calculators' },
  'discount-calculator': { slug: 'discount-calculator', name: 'Discount Calculator', shortIntro: 'Find the final price after any discount and see how much you save.', category: 'Finance Calculators' },
  'json-formatter': { slug: 'json-formatter', name: 'JSON Formatter', shortIntro: 'Format and validate JSON with proper indentation.', category: 'Developer Tools' },
  'jwt-decoder': { slug: 'jwt-decoder', name: 'JWT Decoder', shortIntro: 'Decode JWT tokens and inspect header, payload, and signature locally.', category: 'Developer Tools' },
  'base64-encoder': { slug: 'base64-encoder', name: 'Base64 Encoder', shortIntro: 'Encode text to Base64 instantly with proper UTF-8 support.', category: 'Developer Tools' },
  'base64-decoder': { slug: 'base64-decoder', name: 'Base64 Decoder', shortIntro: 'Decode Base64 back to text instantly.', category: 'Developer Tools' },
  'regex-tester': { slug: 'regex-tester', name: 'Regex Tester & Explainer', shortIntro: 'Test regex with live highlighted matches and a syntax cheat sheet.', category: 'Developer Tools' },
  'uuid-generator': { slug: 'uuid-generator', name: 'UUID Generator', shortIntro: 'Generate random v4 UUIDs for databases, sessions, and APIs.', category: 'Developer Tools' },
  'curl-converter': { slug: 'curl-converter', name: 'Curl to Code Converter', shortIntro: 'Turn curl commands into JavaScript (Fetch/Axios) and Python requests code.', category: 'Developer Tools' },
  'markdown-to-html': { slug: 'markdown-to-html', name: 'Markdown to HTML Converter', shortIntro: 'Turn Markdown into clean HTML with live preview.', category: 'Developer Tools' },
  'hash-generator': { slug: 'hash-generator', name: 'Hash Generator (SHA-256)', shortIntro: 'Generate SHA-256 and SHA-1 hashes from text.', category: 'Developer Tools' },
  'binary-to-text': { slug: 'binary-to-text', name: 'Binary to Text Converter', shortIntro: 'Decode binary back to readable text.', category: 'Developer Tools' },
  'text-to-binary': { slug: 'text-to-binary', name: 'Text to Binary Converter', shortIntro: 'Convert text characters to binary representation.', category: 'Developer Tools' },
  'url-query-parser': { slug: 'url-query-parser', name: 'URL Query Parser', shortIntro: 'Extract URL query parameters into a JSON object.', category: 'Developer Tools' },
  'text-size-estimator': { slug: 'text-size-estimator', name: 'Text Size Estimator', shortIntro: 'Estimate byte size of your text in various formats.', category: 'Developer Tools' },
  'json-minifier': { slug: 'json-minifier', name: 'JSON Minifier', shortIntro: 'Remove all whitespace to minimize JSON size.', category: 'Developer Tools' },
  'csv-to-json': { slug: 'csv-to-json', name: 'CSV to JSON Converter', shortIntro: 'Convert CSV data to a JSON array using the header row.', category: 'Developer Tools' },
  'json-to-csv': { slug: 'json-to-csv', name: 'JSON to CSV Converter', shortIntro: 'Convert a JSON array of objects to CSV format.', category: 'Developer Tools' },
  'lorem-ipsum-generator': { slug: 'lorem-ipsum-generator', name: 'Lorem Ipsum Generator', shortIntro: 'Generate placeholder text for mockups and designs.', category: 'Developer Tools' },
  'random-number-generator': { slug: 'random-number-generator', name: 'Random Number Generator', shortIntro: 'Generate random numbers in any range, with optional uniqueness.', category: 'Developer Tools' },
  'html-escape': { slug: 'html-escape', name: 'HTML Escape', shortIntro: 'Escape HTML special characters to prevent XSS attacks.', category: 'Developer Tools' },
  'html-unescape': { slug: 'html-unescape', name: 'HTML Unescape', shortIntro: 'Convert HTML entities back to readable characters.', category: 'Developer Tools' },
  'url-encoder': { slug: 'url-encoder', name: 'URL Encoder', shortIntro: 'Encode text for safe use in URLs.', category: 'Developer Tools' },
  'url-decoder': { slug: 'url-decoder', name: 'URL Decoder', shortIntro: 'Decode percent-encoded URLs back to text.', category: 'Developer Tools' },
  'slug-generator': { slug: 'slug-generator', name: 'Slug Generator', shortIntro: 'Convert titles into clean, SEO-friendly URL slugs instantly.', category: 'Developer Tools' },
  'json-to-typescript': { slug: 'json-to-typescript', name: 'JSON to TypeScript', shortIntro: 'Paste JSON and generate clean, nested TypeScript interfaces instantly.', category: 'Developer Tools' },
  'yaml-to-json': { slug: 'yaml-to-json', name: 'YAML to JSON Converter', shortIntro: 'Paste YAML and get clean, formatted JSON instantly.', category: 'Developer Tools' },
  'sql-formatter': { slug: 'sql-formatter', name: 'SQL Formatter', shortIntro: 'Beautify SQL queries with clean indentation and uppercase keywords.', category: 'Developer Tools' },
  'image-to-base64': { slug: 'image-to-base64', name: 'Image to Base64 Converter', shortIntro: 'Turn an image into a Base64 data URI for inline embedding.', category: 'Developer Tools' },
  'word-counter': { slug: 'word-counter', name: 'Word Counter', shortIntro: 'Count words, characters, sentences, and reading time instantly.', category: 'Text Tools' },
  'text-diff': { slug: 'text-diff', name: 'Text Diff Checker', shortIntro: 'Compare two texts and see what changed.', category: 'Text Tools' },
  'remove-line-breaks': { slug: 'remove-line-breaks', name: 'Remove Line Breaks', shortIntro: 'Join multi-line text into a single line.', category: 'Text Tools' },
  'find-and-replace': { slug: 'find-and-replace', name: 'Find and Replace Text', shortIntro: 'Find and replace any text instantly.', category: 'Text Tools' },
  'uppercase-converter': { slug: 'uppercase-converter', name: 'Uppercase Converter', shortIntro: 'Convert any text to ALL UPPERCASE instantly.', category: 'Text Tools' },
  'lowercase-converter': { slug: 'lowercase-converter', name: 'Lowercase Converter', shortIntro: 'Convert any text to lowercase instantly.', category: 'Text Tools' },
  'title-case-converter': { slug: 'title-case-converter', name: 'Title Case Converter', shortIntro: 'Capitalize the first letter of each word for titles and headings.', category: 'Text Tools' },
  'sentence-case-converter': { slug: 'sentence-case-converter', name: 'Sentence Case Converter', shortIntro: 'Capitalize the first letter of each sentence automatically.', category: 'Text Tools' },
  'slug-to-title': { slug: 'slug-to-title', name: 'Slug to Title Converter', shortIntro: 'Convert URL slugs back to readable titles.', category: 'Text Tools' },
  'html-tag-stripper': { slug: 'html-tag-stripper', name: 'HTML Tag Stripper', shortIntro: 'Remove all HTML tags to get clean readable text.', category: 'Text Tools' },
  'character-frequency': { slug: 'character-frequency', name: 'Character Frequency Counter', shortIntro: 'Count how often each character appears in text.', category: 'Text Tools' },
  'email-extractor': { slug: 'email-extractor', name: 'Email Extractor', shortIntro: 'Pull all email addresses out of any text.', category: 'Text Tools' },
  'url-extractor': { slug: 'url-extractor', name: 'URL Extractor', shortIntro: 'Pull all web links out of any text.', category: 'Text Tools' },
  'add-line-numbers': { slug: 'add-line-numbers', name: 'Add Line Numbers', shortIntro: 'Add line numbers to each line of your text.', category: 'Text Tools' },
  'text-to-list': { slug: 'text-to-list', name: 'Text to List Converter', shortIntro: 'Add bullet points to each line of text.', category: 'Text Tools' },
  'reverse-text': { slug: 'reverse-text', name: 'Reverse Text Generator', shortIntro: 'Reverse any text — fun for puzzles and ciphers.', category: 'Text Tools' },
  'remove-duplicate-lines': { slug: 'remove-duplicate-lines', name: 'Remove Duplicate Lines', shortIntro: 'Clean up lists by removing duplicate lines while keeping order.', category: 'Text Tools' },
  'sort-lines': { slug: 'sort-lines', name: 'Sort Text Lines', shortIntro: 'Sort any list alphabetically in one click.', category: 'Text Tools' },
  'whitespace-remover': { slug: 'whitespace-remover', name: 'Whitespace Remover', shortIntro: 'Clean up messy spacing in any text.', category: 'Text Tools' },
  'list-diff': { slug: 'list-diff', name: 'List Diff & Intersection Checker', shortIntro: 'Compare two lists to find unique and common items instantly.', category: 'Text Tools' },
  'mass-converter': { slug: 'mass-converter', name: 'Mass Converter', shortIntro: 'Convert between metric, carats, and grains.', category: 'Unit Converters' },
  'density-converter': { slug: 'density-converter', name: 'Density Converter', shortIntro: 'Convert between density units for physics and chemistry.', category: 'Unit Converters' },
  'power-converter': { slug: 'power-converter', name: 'Power Converter', shortIntro: 'Convert between watts, kilowatts, horsepower, and BTU.', category: 'Unit Converters' },
  'flow-rate-converter': { slug: 'flow-rate-converter', name: 'Flow Rate Converter', shortIntro: 'Convert between L/min, GPM, CFM and more flow units.', category: 'Unit Converters' },
  'data-storage-converter': { slug: 'data-storage-converter', name: 'Data Storage Converter', shortIntro: 'Convert between bytes, KB, MB, GB, TB and more.', category: 'Unit Converters' },
  'time-converter': { slug: 'time-converter', name: 'Time Converter', shortIntro: 'Convert between seconds, minutes, hours, days and more.', category: 'Unit Converters' },
  'numeral-system-converter': { slug: 'numeral-system-converter', name: 'Number Base Converter', shortIntro: 'Convert between binary, octal, decimal, and hex.', category: 'Unit Converters' },
  'angle-converter': { slug: 'angle-converter', name: 'Angle Converter', shortIntro: 'Convert between degrees, radians, and gradians.', category: 'Unit Converters' },
  'fuel-economy-converter': { slug: 'fuel-economy-converter', name: 'Fuel Economy Converter', shortIntro: 'Convert between MPG and L/100km for car efficiency.', category: 'Unit Converters' },
  'pressure-converter': { slug: 'pressure-converter', name: 'Pressure Converter', shortIntro: 'Convert between bar, PSI, pascal, atm and more.', category: 'Unit Converters' },
  'energy-converter': { slug: 'energy-converter', name: 'Energy Converter', shortIntro: 'Convert between joules, calories, kWh, and BTU.', category: 'Unit Converters' },
  'frequency-converter': { slug: 'frequency-converter', name: 'Frequency Converter', shortIntro: 'Convert between Hz, kHz, MHz, GHz, and RPM.', category: 'Unit Converters' },
  'weight-converter': { slug: 'weight-converter', name: 'Weight Converter', shortIntro: 'Convert between metric and imperial weight units instantly.', category: 'Unit Converters' },
  'temperature-converter': { slug: 'temperature-converter', name: 'Temperature Converter', shortIntro: 'Convert between Celsius, Fahrenheit, and Kelvin instantly.', category: 'Unit Converters' },
  'speed-converter': { slug: 'speed-converter', name: 'Speed Converter', shortIntro: 'Convert between km/h, mph, m/s, knots, and ft/s instantly.', category: 'Unit Converters' },
  'area-converter': { slug: 'area-converter', name: 'Area Converter', shortIntro: 'Convert between metric and imperial area units, including acres and hectares.', category: 'Unit Converters' },
  'volume-converter': { slug: 'volume-converter', name: 'Volume Converter', shortIntro: 'Convert between metric and US cooking volume units instantly.', category: 'Unit Converters' },
  'length-converter': { slug: 'length-converter', name: 'Length Converter', shortIntro: 'Convert between metric and imperial length units instantly.', category: 'Unit Converters' },
  'trapezoid-calculator': { slug: 'trapezoid-calculator', name: 'Trapezoid Calculator', shortIntro: 'Find trapezoid area from two parallel sides and height.', category: 'Math Calculators' },
  'cube-calculator': { slug: 'cube-calculator', name: 'Cube Calculator', shortIntro: 'Find cube volume and surface area.', category: 'Math Calculators' },
  'sphere-calculator': { slug: 'sphere-calculator', name: 'Sphere Calculator', shortIntro: 'Find sphere volume and surface area from radius.', category: 'Math Calculators' },
  'scientific-notation-converter': { slug: 'scientific-notation-converter', name: 'Scientific Notation Converter', shortIntro: 'Convert numbers to scientific, E-, and engineering notation.', category: 'Math Calculators' },
  'prime-number-checker': { slug: 'prime-number-checker', name: 'Prime Number Checker', shortIntro: 'Check if any number is prime and find adjacent primes.', category: 'Math Calculators' },
  'prime-factorization-calculator': { slug: 'prime-factorization-calculator', name: 'Prime Factorization Calculator', shortIntro: 'Decompose any number into its prime factors.', category: 'Math Calculators' },
  'combination-calculator': { slug: 'combination-calculator', name: 'Combination Calculator', shortIntro: 'Calculate combinations (n choose r) for probability and odds.', category: 'Math Calculators' },
  'permutation-calculator': { slug: 'permutation-calculator', name: 'Permutation Calculator', shortIntro: 'Calculate permutations (arrangements where order matters).', category: 'Math Calculators' },
  'circle-calculator': { slug: 'circle-calculator', name: 'Circle Calculator', shortIntro: 'Find circle area, circumference, and diameter from radius.', category: 'Math Calculators' },
  'triangle-calculator': { slug: 'triangle-calculator', name: 'Triangle Calculator', shortIntro: 'Solve right triangles — hypotenuse, area, perimeter.', category: 'Math Calculators' },
  'rectangle-calculator': { slug: 'rectangle-calculator', name: 'Rectangle Calculator', shortIntro: 'Find rectangle area, perimeter, and diagonal.', category: 'Math Calculators' },
  'standard-deviation-calculator': { slug: 'standard-deviation-calculator', name: 'Standard Deviation Calculator', shortIntro: 'Calculate standard deviation, variance, and mean.', category: 'Math Calculators' },
  'percentile-calculator': { slug: 'percentile-calculator', name: 'Percentile Calculator', shortIntro: 'Find the value at any percentile of your data.', category: 'Math Calculators' },
  'fraction-calculator': { slug: 'fraction-calculator', name: 'Fraction Calculator', shortIntro: 'Add, subtract, multiply, divide fractions with exact math.', category: 'Math Calculators' },
  'ratio-calculator': { slug: 'ratio-calculator', name: 'Ratio Calculator', shortIntro: 'Solve proportions and find missing ratio values.', category: 'Math Calculators' },
  'lcm-gcd-calculator': { slug: 'lcm-gcd-calculator', name: 'LCM & GCD Calculator', shortIntro: 'Find LCM and GCD of any set of numbers.', category: 'Math Calculators' },
  'average-calculator': { slug: 'average-calculator', name: 'Average Calculator', shortIntro: 'Calculate mean, median, sum, min, max, and range of any number list.', category: 'Math Calculators' },
  'percentage-calculator': { slug: 'percentage-calculator', name: 'Percentage Calculator', shortIntro: 'Calculate percentages, increases, decreases, and discounts instantly.', category: 'Math Calculators' },
  'bmi-calculator': { slug: 'bmi-calculator', name: 'BMI Calculator', shortIntro: 'Calculate your Body Mass Index and see your healthy weight range.', category: 'Health Calculators' },
  'calorie-calculator': { slug: 'calorie-calculator', name: 'Calorie Calculator', shortIntro: 'Find your daily calorie needs for weight loss or gain.', category: 'Health Calculators' },
  'tdee-calculator': { slug: 'tdee-calculator', name: 'TDEE Calculator', shortIntro: 'Find your daily calorie needs (TDEE) for cutting, maintaining, or bulking.', category: 'Health Calculators' },
  'bmr-calculator': { slug: 'bmr-calculator', name: 'BMR Calculator', shortIntro: 'Calculate calories your body burns at complete rest.', category: 'Health Calculators' },
  'body-fat-calculator': { slug: 'body-fat-calculator', name: 'Body Fat Calculator', shortIntro: 'Estimate body fat % using circumference measurements.', category: 'Health Calculators' },
  'macro-calculator': { slug: 'macro-calculator', name: 'Macro Calculator', shortIntro: 'Split daily calories into protein, carbs, and fat.', category: 'Health Calculators' },
  'pregnancy-due-date-calculator': { slug: 'pregnancy-due-date-calculator', name: 'Pregnancy Due Date Calculator', shortIntro: 'Estimate due date from your last menstrual period.', category: 'Health Calculators' },
  'water-intake-calculator': { slug: 'water-intake-calculator', name: 'Water Intake Calculator', shortIntro: 'Find your ideal daily water intake.', category: 'Health Calculators' },
  'ideal-weight-calculator': { slug: 'ideal-weight-calculator', name: 'Ideal Weight Calculator', shortIntro: 'Find your ideal body weight based on height and gender.', category: 'Health Calculators' },
  'svg-to-image': { slug: 'svg-to-image', name: 'SVG to PNG Converter', shortIntro: 'Convert SVG to PNG or WebP in-browser with custom scale and download.', category: 'Web Design Tools' },
  'px-to-rem': { slug: 'px-to-rem', name: 'PX to REM / EM Converter', shortIntro: 'Convert pixels to rem and em with a custom root font size.', category: 'Web Design Tools' },
  'aspect-ratio-calculator': { slug: 'aspect-ratio-calculator', name: 'Aspect Ratio Calculator', shortIntro: 'Compute missing width or height to keep any aspect ratio.', category: 'Web Design Tools' },
  'color-contrast-checker': { slug: 'color-contrast-checker', name: 'Color Contrast Checker (WCAG)', shortIntro: 'Test color contrast against WCAG AA and AAA accessibility levels.', category: 'Web Design Tools' },
  'color-converter': { slug: 'color-converter', name: 'Color Converter', shortIntro: 'Convert between HEX, RGB, and HSL with a visual picker.', category: 'Web Design Tools' },
  'open-graph-generator': { slug: 'open-graph-generator', name: 'Open Graph & Meta Tag Generator', shortIntro: 'Build OG and Twitter Card meta tags with a live social share preview.', category: 'Web Design Tools' },
  'css-shadow-generator': { slug: 'css-shadow-generator', name: 'CSS Box Shadow & Glassmorphism Generator', shortIntro: 'Tune box-shadow and glassmorphism visually, preview live, copy the CSS.', category: 'Web Design Tools' },
  'favicon-generator': { slug: 'favicon-generator', name: 'Favicon Generator', shortIntro: 'Turn an image into 16x16, 32x32 favicons and an Apple Touch Icon.', category: 'Web Design Tools' },
  'cron-parser': { slug: 'cron-parser', name: 'Cron Expression Parser', shortIntro: 'Turn a cron expression into plain English and see the next 5 fire times.', category: 'Time Calculators' },
  'age-calculator': { slug: 'age-calculator', name: 'Age Calculator', shortIntro: 'Calculate exact age in years, months, days, or time between any two dates.', category: 'Time Calculators' },
  'date-difference-calculator': { slug: 'date-difference-calculator', name: 'Date Difference Calculator', shortIntro: 'Find exact duration between any two dates — days, weeks, months, business days.', category: 'Time Calculators' },
  'age-difference-calculator': { slug: 'age-difference-calculator', name: 'Age Difference Calculator', shortIntro: 'Find the age gap between two people.', category: 'Time Calculators' },
  'grade-calculator': { slug: 'grade-calculator', name: 'Grade Calculator', shortIntro: 'Find your grade percentage and letter from points.', category: 'Education Calculators' },
  'final-grade-calculator': { slug: 'final-grade-calculator', name: 'Final Grade Calculator', shortIntro: 'Find the final exam score needed for your target grade.', category: 'Education Calculators' },
  'gpa-calculator': { slug: 'gpa-calculator', name: 'GPA Calculator', shortIntro: 'Calculate your GPA instantly. Add courses, credits, and letter grades.', category: 'Education Calculators' },
  'password-strength-checker': { slug: 'password-strength-checker', name: 'Password Strength Checker', shortIntro: 'Test your password strength with entropy analysis and a checklist.', category: 'Security Tools' },
  'password-generator': { slug: 'password-generator', name: 'Password Generator', shortIntro: 'Create strong, random, and secure passwords in one click.', category: 'Security Tools' },
  'qr-code-generator': { slug: 'qr-code-generator', name: 'QR Code Generator', shortIntro: 'Create custom QR codes for URLs, text, and WiFi. Free, no watermark.', category: 'Business Tools' },
  'gpt-token-counter': { slug: 'gpt-token-counter', name: 'GPT Token Counter', shortIntro: 'Estimate tokens and API cost for GPT and Claude prompts.', category: 'AI Tools' },
  'ip-subnet-calculator': { slug: 'ip-subnet-calculator', name: 'IP Subnet Calculator', shortIntro: 'Compute netmask, network, broadcast, and host range from CIDR.', category: 'Developer Tools' },
  'chmod-calculator': { slug: 'chmod-calculator', name: 'Chmod Calculator', shortIntro: 'Convert between octal 755 and symbolic rwxr-xr-x permissions.', category: 'Developer Tools' },
  'ssh-key-generator': { slug: 'ssh-key-generator', name: 'SSH Key Generator', shortIntro: 'Generate RSA or Ed25519 SSH key pairs in your browser.', category: 'Security Tools' },
  'bcrypt-hash-generator': { slug: 'bcrypt-hash-generator', name: 'Bcrypt Hash Generator', shortIntro: 'Hash and verify passwords with bcrypt or salted SHA in-browser.', category: 'Security Tools' },
  'user-agent-parser': { slug: 'user-agent-parser', name: 'User Agent Parser', shortIntro: 'Decode user-agent strings into browser, OS, engine, and device.', category: 'Developer Tools' },
  'json-schema-generator': { slug: 'json-schema-generator', name: 'JSON Schema Generator', shortIntro: 'Turn any JSON payload into a Draft-07 JSON Schema.', category: 'Developer Tools' },
  'naming-case-converter': { slug: 'naming-case-converter', name: 'Naming Case Converter', shortIntro: 'Convert names between camelCase, snake_case, kebab-case, and more.', category: 'Developer Tools' },
  'nginx-config-generator': { slug: 'nginx-config-generator', name: 'Nginx Config Generator', shortIntro: 'Build a reverse proxy nginx server block with SSL and caching.', category: 'Developer Tools' },
  'webp-to-png-converter': { slug: 'webp-to-png-converter', name: 'WebP to PNG Converter', shortIntro: 'Convert WebP images to PNG or JPG in your browser.', category: 'Web Design Tools' },
  'png-to-webp-converter': { slug: 'png-to-webp-converter', name: 'PNG to WebP Converter', shortIntro: 'Convert PNG/JPG to WebP and see the size savings.', category: 'Web Design Tools' },
  'image-resizer': { slug: 'image-resizer', name: 'Image Resizer', shortIntro: 'Resize and compress images with live file-size preview.', category: 'Web Design Tools' },
  'svg-minifier': { slug: 'svg-minifier', name: 'SVG Minifier', shortIntro: 'Strip comments, metadata, and whitespace from SVG files.', category: 'Web Design Tools' },
  'css-gradient-generator': { slug: 'css-gradient-generator', name: 'CSS Gradient Generator', shortIntro: 'Build linear, radial, and mesh gradients with live preview.', category: 'Web Design Tools' },
  'css-clamp-calculator': { slug: 'css-clamp-calculator', name: 'CSS Clamp Calculator', shortIntro: 'Generate fluid font sizes with CSS clamp().', category: 'Web Design Tools' },
  'csv-to-markdown-table': { slug: 'csv-to-markdown-table', name: 'CSV to Markdown Table', shortIntro: 'Turn CSV/TSV data into GitHub-ready Markdown tables.', category: 'Text Tools' },
  'text-cleaner': { slug: 'text-cleaner', name: 'Text Cleaner', shortIntro: 'Strip emojis, accents, and special characters from text.', category: 'Text Tools' },
  'srt-subtitle-shift': { slug: 'srt-subtitle-shift', name: 'SRT Subtitle Shifter', shortIntro: 'Shift subtitle timings by any offset and strip formatting.', category: 'Text Tools' },
  'code-beautifier': { slug: 'code-beautifier', name: 'Code Beautifier', shortIntro: 'Format and indent minified HTML, CSS, JS, and JSON.', category: 'Developer Tools' },
  'secret-key-generator': { slug: 'secret-key-generator', name: 'Secret Key Generator', shortIntro: 'Generate high-entropy API keys and secrets in your browser.', category: 'Security Tools' },
  'auto-loan-calculator': { slug: 'auto-loan-calculator', name: 'Auto Loan Calculator', shortIntro: 'Calculate car payments with down payment, trade-in, and tax.', category: 'Finance Calculators' },
  'ebay-fee-calculator': { slug: 'ebay-fee-calculator', name: 'eBay Fee Calculator', shortIntro: 'See exactly what you net after eBay or Etsy fees.', category: 'Finance Calculators' },
  'saas-ltv-churn-calculator': { slug: 'saas-ltv-churn-calculator', name: 'SaaS LTV Calculator', shortIntro: 'Model LTV, churn, CAC payback, and LTV:CAC for your SaaS.', category: 'Business Tools' },
  'freelance-invoice-generator': { slug: 'freelance-invoice-generator', name: 'Invoice Generator', shortIntro: 'Build, preview, and print professional invoices for free.', category: 'Business Tools' },
  'reverse-stripe-fee-calculator': { slug: 'reverse-stripe-fee-calculator', name: 'Reverse Stripe Fee Calculator', shortIntro: 'Find how much to charge so you net exactly what you want.', category: 'Finance Calculators' },
  'timezone-converter': { slug: 'timezone-converter', name: 'Timezone Converter', shortIntro: 'Convert times across zones and find meeting-friendly hours.', category: 'Time Calculators' },
  'days-countdown-calculator': { slug: 'days-countdown-calculator', name: 'Days Countdown Calculator', shortIntro: 'Live countdown to any date, or days between two dates.', category: 'Time Calculators' },
  'reading-speaking-time': { slug: 'reading-speaking-time', name: 'Reading Time Calculator', shortIntro: 'Estimate reading and speaking time for any text.', category: 'Time Calculators' },
  'random-choice-picker': { slug: 'random-choice-picker', name: 'Random Choice Picker', shortIntro: 'Paste options, spin, and let chance decide for you.', category: 'Developer Tools' },
  'wordle-solver': { slug: 'wordle-solver', name: 'Wordle Solver', shortIntro: 'Narrow down Wordle answers by known, included, and excluded letters.', category: 'Text Tools' },
  'ip-checker': { slug: 'ip-checker', name: 'IP Quality & Fraud Checker', shortIntro: 'Inspect IP quality, ASN type, fraud score, and timezone consistency.', category: 'Developer Tools' },
  'epoch-converter': { slug: 'epoch-converter', name: 'Epoch Converter', shortIntro: 'Convert Unix timestamps to dates and back, in UTC or local time.', category: 'Developer Tools' },
  'json-diff': { slug: 'json-diff', name: 'JSON Diff Checker', shortIntro: 'Compare two JSON payloads field by field, order-insensitive.', category: 'Developer Tools' },
  'line-diff-checker': { slug: 'line-diff-checker', name: 'Line Diff Checker', shortIntro: 'Line-by-line diff with additions, deletions, and change counts.', category: 'Text Tools' },
  'robots-txt-generator': { slug: 'robots-txt-generator', name: 'Robots.txt Generator', shortIntro: 'Build a correct robots.txt with presets and live preview.', category: 'Developer Tools' },
  'roman-numeral-converter': { slug: 'roman-numeral-converter', name: 'Roman Numeral Converter', shortIntro: 'Two-way Roman numeral conversion with a quick reference chart.', category: 'Math Calculators' },
  'pace-calculator': { slug: 'pace-calculator', name: 'Running Pace Calculator', shortIntro: 'Pace, finish-time prediction, and split table for any race distance.', category: 'Health Calculators' },
  'protein-intake-calculator': { slug: 'protein-intake-calculator', name: 'Protein Intake Calculator', shortIntro: 'Daily protein target in grams, tuned to your weight and goal.', category: 'Health Calculators' },
  'electricity-cost-calculator': { slug: 'electricity-cost-calculator', name: 'Electricity Cost Calculator', shortIntro: 'What any appliance really costs per day, month, and year.', category: 'Finance Calculators' },
  'sleep-calculator': { slug: 'sleep-calculator', name: 'Sleep Cycle Calculator', shortIntro: 'Bedtimes built around 90-minute sleep cycles so you wake refreshed.', category: 'Health Calculators' },
  'cooking-converter': { slug: 'cooking-converter', name: 'Cooking Measurement Converter', shortIntro: 'Cups ↔ grams ↔ ounces, adjusted per ingredient density.', category: 'Unit Converters' },
  'fuel-cost-calculator': { slug: 'fuel-cost-calculator', name: 'Fuel Cost Calculator', shortIntro: 'Gas money for any trip — one-way, round trip, split per person.', category: 'Finance Calculators' },
  'subscription-cost-calculator': { slug: 'subscription-cost-calculator', name: 'Subscription Cost Calculator', shortIntro: 'Total up every subscription and see the yearly damage.', category: 'Finance Calculators' },
  'overtime-calculator': { slug: 'overtime-calculator', name: 'Overtime Pay Calculator', shortIntro: 'Weekly pay with time-and-a-half, double time, or custom multipliers.', category: 'Finance Calculators' },
  'take-home-pay-calculator': { slug: 'take-home-pay-calculator', name: 'Take-Home Pay Calculator', shortIntro: 'Estimate net pay after federal tax, FICA, and pre-tax deductions.', category: 'Finance Calculators' },
  'wedding-budget-calculator': { slug: 'wedding-budget-calculator', name: 'Wedding Budget Calculator', shortIntro: 'Turn your total into per-category amounts with typical percentages.', category: 'Finance Calculators' },
  'amortization-table-generator': { slug: 'amortization-table-generator', name: 'Amortization Table Generator', shortIntro: 'Full payment-by-payment schedule with running balance, CSV export.', category: 'Finance Calculators' },
  'heart-rate-zone-calculator': { slug: 'heart-rate-zone-calculator', name: 'Heart Rate Zone Calculator', shortIntro: 'Your five training zones, personalized with resting heart rate.', category: 'Health Calculators' },
  'caffeine-calculator': { slug: 'caffeine-calculator', name: 'Caffeine Calculator', shortIntro: 'Estimate the caffeine still in your system right now.', category: 'Health Calculators' },
  'steps-to-calories-calculator': { slug: 'steps-to-calories-calculator', name: 'Steps to Calories Calculator', shortIntro: 'Steps → calories and distance, adjusted for your body.', category: 'Health Calculators' },
  'paint-calculator': { slug: 'paint-calculator', name: 'Paint Calculator', shortIntro: 'Gallons or liters of paint for a room, coats and openings counted.', category: 'Home Calculators' },
  'dog-age-calculator': { slug: 'dog-age-calculator', name: 'Dog Age Calculator', shortIntro: 'Dog-to-human age conversion that respects breed size — no ×7 myth.', category: 'Pet Tools' },
  'keycode-info': { slug: 'keycode-info', name: 'Keyboard Event Info (Keycode)', shortIntro: 'Press any key — see key, code, keyCode, and modifiers live.', category: 'Developer Tools' },
  'mime-type-lookup': { slug: 'mime-type-lookup', name: 'MIME Type Lookup', shortIntro: 'Extension ↔ MIME type mapping for HTTP headers and configs.', category: 'Developer Tools' },
  'xml-formatter': { slug: 'xml-formatter', name: 'XML Formatter & Validator', shortIntro: 'Pretty-print, minify, or pinpoint-validate XML documents.', category: 'Developer Tools' },
  'markdown-toc-generator': { slug: 'markdown-toc-generator', name: 'Markdown TOC Generator', shortIntro: 'Linked outline from your headings, GitHub-slug compatible.', category: 'Text Tools' },
  'log-filter-tool': { slug: 'log-filter-tool', name: 'Log Filter & Grep Tool', shortIntro: 'Grep-style filtering for logs — keyword, level, or regex.', category: 'Developer Tools' },
  'ascii-table': { slug: 'ascii-table', name: 'ASCII Table', shortIntro: 'Every ASCII character with dec/hex/oct/bin codes, searchable.', category: 'Developer Tools' },
  'screen-time-calculator': { slug: 'screen-time-calculator', name: 'Screen Time Calculator', shortIntro: 'Daily scrolling hours, translated into years of your life.', category: 'Time Calculators' },
  'reading-level-checker': { slug: 'reading-level-checker', name: 'Reading Level Checker', shortIntro: 'Flesch scores and grade level with sentence-level breakdown.', category: 'Text Tools' },
  'hmac-generator': { slug: 'hmac-generator', name: 'HMAC Generator', shortIntro: 'HMAC-SHA256/384/512 signatures via native WebCrypto.', category: 'Security Tools' },
  'jwt-generator': { slug: 'jwt-generator', name: 'JWT Generator', shortIntro: 'Craft signed JWTs locally — pairs with our decoder for testing.', category: 'Developer Tools' },
  'hash-comparator': { slug: 'hash-comparator', name: 'Hash Comparator', shortIntro: 'Constant-time comparison of two hashes — no timing leaks.', category: 'Security Tools' },
  'base-converter': { slug: 'base-converter', name: 'Base Converter (Any Base 2-36)', shortIntro: 'Any base 2-36, fractions included, all common bases at once.', category: 'Developer Tools' },
  'cron-expression-generator': { slug: 'cron-expression-generator', name: 'Cron Expression Generator', shortIntro: 'Click-to-build cron schedules with live plain-English preview.', category: 'Developer Tools' },
  'htaccess-redirect-generator': { slug: 'htaccess-redirect-generator', name: '.htaccess Redirect Generator', shortIntro: '301s, domain moves, HTTPS and canonical rules without tears.', category: 'Developer Tools' },
  'unicode-character-lookup': { slug: 'unicode-character-lookup', name: 'Unicode Character Lookup', shortIntro: 'Find any symbol by name or paste — code point and block shown.', category: 'Developer Tools' },
  'toml-to-json': { slug: 'toml-to-json', name: 'TOML to JSON Converter', shortIntro: 'Cargo/pyproject-style TOML parsed to clean JSON locally.', category: 'Developer Tools' },
  'dice-roller': { slug: 'dice-roller', name: 'Dice Roller', shortIntro: 'Roll any dice — d4 to d100, multiples at once, fair rolls.', category: 'Game Tools' },
  'coin-flip': { slug: 'coin-flip', name: 'Coin Flip', shortIntro: 'A crisp instant heads-or-tails with a running tally.', category: 'Game Tools' },
  'wheel-spinner': { slug: 'wheel-spinner', name: 'Wheel Spinner', shortIntro: 'Spin to decide: names, chores, restaurants — fairly chosen.', category: 'Game Tools' },
  'morse-code-translator': { slug: 'morse-code-translator', name: 'Morse Code Translator', shortIntro: 'Two-way Morse translation with dot-dash view and beep audio.', category: 'Text Tools' },
  'typing-speed-test': { slug: 'typing-speed-test', name: 'Typing Speed Test', shortIntro: 'One-minute WPM and accuracy test — clean and ad-free.', category: 'Text Tools' },
  'random-team-generator': { slug: 'random-team-generator', name: 'Random Team Generator', shortIntro: 'Fairly split any list into teams — reshuffle till it feels right.', category: 'Game Tools' },
  'password-entropy-checker': { slug: 'password-entropy-checker', name: 'Password Entropy Checker', shortIntro: 'Entropy in bits — the honest measure of password strength.', category: 'Security Tools' },
  'llm-cost-calculator': { slug: 'llm-cost-calculator', name: 'LLM API Cost Calculator', shortIntro: 'Per-request and monthly API costs across 17 models, side by side.', category: 'AI Tools' },
  'context-window-checker': { slug: 'context-window-checker', name: 'Context Window Checker', shortIntro: 'Token count vs every model context limit, with headroom percentages.', category: 'AI Tools' },
  'json-to-zod': { slug: 'json-to-zod', name: 'JSON to Zod Schema', shortIntro: 'Paste JSON, get a typed Zod schema — AI output validation ready.', category: 'AI Tools' },
  'aes-encrypt-decrypt': { slug: 'aes-encrypt-decrypt', name: 'AES Encrypt & Decrypt', shortIntro: 'AES-256-GCM in-browser: authenticated, PBKDF2-keyed, zero upload.', category: 'Security Tools' },
  'car-cost-calculator': { slug: 'car-cost-calculator', name: 'Car Cost Calculator', shortIntro: 'Total ownership cost: fuel, insurance, maintenance, depreciation, financing.', category: 'Finance Calculators' },
  'json-repair': { slug: 'json-repair', name: 'JSON Repair', shortIntro: 'Rescue malformed LLM JSON — truncated, trailing commas, fences.', category: 'AI Tools' },
  'markdown-fence-extractor': { slug: 'markdown-fence-extractor', name: 'Code Block Extractor', shortIntro: 'Pull every ``` code block out of Markdown or AI answers.', category: 'AI Tools' },
  'prompt-template-filler': { slug: 'prompt-template-filler', name: 'Prompt Template Filler', shortIntro: 'Fill {{variables}} in prompt templates from JSON — live preview.', category: 'AI Tools' },
  'openai-tools-builder': { slug: 'openai-tools-builder', name: 'OpenAI Tools JSON Builder', shortIntro: 'Form-built tool definitions → clean tools JSON for LLM APIs.', category: 'AI Tools' },
  'csv-to-finetune-jsonl': { slug: 'csv-to-finetune-jsonl', name: 'CSV to Fine-tuning JSONL', shortIntro: 'CSV training rows → OpenAI chat-format JSONL, mapped and validated.', category: 'AI Tools' },
  'token-visualizer': { slug: 'token-visualizer', name: 'Token Visualizer', shortIntro: 'Color-coded token boundaries with counts — see what models see.', category: 'AI Tools' },
  'embedding-price-calculator': { slug: 'embedding-price-calculator', name: 'Embedding Price Calculator', shortIntro: 'Embedding costs across models: dimensions, $/1M tokens, workload totals.', category: 'AI Tools' },
}

/** slug → Related Tools 推荐(4 款,排序与 lib/tools.ts#getRelatedTools 一致) */
export const relatedIndex: Record<string, string[]> = {
  'loan-calculator': ['compound-interest-calculator', 'amortization-table-generator', 'annuity-calculator', 'apy-calculator'],
  'mortgage-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'compound-interest-calculator': ['loan-calculator', 'amortization-table-generator', 'annuity-calculator', 'apy-calculator'],
  'apy-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'roi-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'credit-card-minimum-payment-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'cash-back-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'down-payment-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'dti-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'commission-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'bill-split-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'savings-goal-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'net-worth-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'annuity-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'apy-calculator'],
  'capital-gains-tax-estimator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'rent-vs-buy-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'inflation-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'retirement-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'simple-interest-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'unit-price-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'markup-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'hourly-to-salary-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'credit-card-payoff-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'income-tax-estimator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'salary-converter': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'sales-tax-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'tip-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'discount-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'json-formatter': ['jwt-decoder', 'ascii-table', 'base-converter', 'base64-decoder'],
  'jwt-decoder': ['json-formatter', 'ascii-table', 'base-converter', 'base64-decoder'],
  'base64-encoder': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'base64-decoder': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'regex-tester': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'uuid-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'curl-converter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'markdown-to-html': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'hash-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'binary-to-text': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'text-to-binary': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'url-query-parser': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'text-size-estimator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'json-minifier': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'csv-to-json': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'json-to-csv': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'lorem-ipsum-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'random-number-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'html-escape': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'html-unescape': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'url-encoder': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'url-decoder': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'slug-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'json-to-typescript': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'yaml-to-json': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'sql-formatter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'image-to-base64': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'word-counter': ['add-line-numbers', 'character-frequency', 'csv-to-markdown-table', 'email-extractor'],
  'text-diff': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'remove-line-breaks': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'find-and-replace': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'uppercase-converter': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'lowercase-converter': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'title-case-converter': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'sentence-case-converter': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'slug-to-title': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'html-tag-stripper': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'character-frequency': ['word-counter', 'add-line-numbers', 'csv-to-markdown-table', 'email-extractor'],
  'email-extractor': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'url-extractor': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'add-line-numbers': ['word-counter', 'character-frequency', 'csv-to-markdown-table', 'email-extractor'],
  'text-to-list': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'reverse-text': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'remove-duplicate-lines': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'sort-lines': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'whitespace-remover': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'list-diff': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'mass-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'density-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'power-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'flow-rate-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'data-storage-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'density-converter'],
  'time-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'numeral-system-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'angle-converter': ['area-converter', 'cooking-converter', 'data-storage-converter', 'density-converter'],
  'fuel-economy-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'pressure-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'energy-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'frequency-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'weight-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'temperature-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'speed-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'area-converter': ['angle-converter', 'cooking-converter', 'data-storage-converter', 'density-converter'],
  'volume-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'length-converter': ['angle-converter', 'area-converter', 'cooking-converter', 'data-storage-converter'],
  'trapezoid-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'cube-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'sphere-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'scientific-notation-converter': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'prime-number-checker': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'prime-factorization-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'combination-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'cube-calculator'],
  'permutation-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'circle-calculator': ['percentage-calculator', 'average-calculator', 'combination-calculator', 'cube-calculator'],
  'triangle-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'rectangle-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'standard-deviation-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'percentile-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'fraction-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'ratio-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'lcm-gcd-calculator': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'average-calculator': ['percentage-calculator', 'circle-calculator', 'combination-calculator', 'cube-calculator'],
  'percentage-calculator': ['average-calculator', 'circle-calculator', 'combination-calculator', 'cube-calculator'],
  'bmi-calculator': ['tdee-calculator', 'bmr-calculator', 'body-fat-calculator', 'caffeine-calculator'],
  'calorie-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'tdee-calculator': ['bmi-calculator', 'bmr-calculator', 'body-fat-calculator', 'caffeine-calculator'],
  'bmr-calculator': ['tdee-calculator', 'bmi-calculator', 'body-fat-calculator', 'caffeine-calculator'],
  'body-fat-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'caffeine-calculator'],
  'macro-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'pregnancy-due-date-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'water-intake-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'ideal-weight-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'svg-to-image': ['aspect-ratio-calculator', 'color-contrast-checker', 'color-converter', 'css-clamp-calculator'],
  'px-to-rem': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'aspect-ratio-calculator': ['svg-to-image', 'color-contrast-checker', 'color-converter', 'css-clamp-calculator'],
  'color-contrast-checker': ['svg-to-image', 'aspect-ratio-calculator', 'color-converter', 'css-clamp-calculator'],
  'color-converter': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'css-clamp-calculator'],
  'open-graph-generator': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'css-shadow-generator': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'favicon-generator': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'cron-parser': ['age-calculator', 'age-difference-calculator', 'date-difference-calculator', 'days-countdown-calculator'],
  'age-calculator': ['cron-parser', 'age-difference-calculator', 'date-difference-calculator', 'days-countdown-calculator'],
  'date-difference-calculator': ['cron-parser', 'age-calculator', 'age-difference-calculator', 'days-countdown-calculator'],
  'age-difference-calculator': ['cron-parser', 'age-calculator', 'date-difference-calculator', 'days-countdown-calculator'],
  'grade-calculator': ['final-grade-calculator', 'gpa-calculator', 'loan-calculator', 'compound-interest-calculator'],
  'final-grade-calculator': ['gpa-calculator', 'grade-calculator', 'loan-calculator', 'compound-interest-calculator'],
  'gpa-calculator': ['final-grade-calculator', 'grade-calculator', 'loan-calculator', 'compound-interest-calculator'],
  'password-strength-checker': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'hmac-generator'],
  'password-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'hmac-generator'],
  'qr-code-generator': ['freelance-invoice-generator', 'saas-ltv-churn-calculator', 'loan-calculator', 'compound-interest-calculator'],
  'gpt-token-counter': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'json-repair'],
  'ip-subnet-calculator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'chmod-calculator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'ssh-key-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'hmac-generator'],
  'bcrypt-hash-generator': ['aes-encrypt-decrypt', 'hash-comparator', 'hmac-generator', 'password-entropy-checker'],
  'user-agent-parser': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'json-schema-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'naming-case-converter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'nginx-config-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'webp-to-png-converter': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'png-to-webp-converter': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'image-resizer': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'svg-minifier': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'css-gradient-generator': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'css-clamp-calculator': ['svg-to-image', 'aspect-ratio-calculator', 'color-contrast-checker', 'color-converter'],
  'csv-to-markdown-table': ['word-counter', 'add-line-numbers', 'character-frequency', 'email-extractor'],
  'text-cleaner': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'srt-subtitle-shift': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'code-beautifier': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'secret-key-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'hmac-generator'],
  'auto-loan-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'ebay-fee-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'saas-ltv-churn-calculator': ['qr-code-generator', 'freelance-invoice-generator', 'loan-calculator', 'compound-interest-calculator'],
  'freelance-invoice-generator': ['qr-code-generator', 'saas-ltv-churn-calculator', 'loan-calculator', 'compound-interest-calculator'],
  'reverse-stripe-fee-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'timezone-converter': ['cron-parser', 'age-calculator', 'age-difference-calculator', 'date-difference-calculator'],
  'days-countdown-calculator': ['cron-parser', 'age-calculator', 'age-difference-calculator', 'date-difference-calculator'],
  'reading-speaking-time': ['cron-parser', 'age-calculator', 'age-difference-calculator', 'date-difference-calculator'],
  'random-choice-picker': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'wordle-solver': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'ip-checker': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'epoch-converter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'json-diff': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'line-diff-checker': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'robots-txt-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'roman-numeral-converter': ['percentage-calculator', 'average-calculator', 'circle-calculator', 'combination-calculator'],
  'pace-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'protein-intake-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'electricity-cost-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'sleep-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'cooking-converter': ['angle-converter', 'area-converter', 'data-storage-converter', 'density-converter'],
  'fuel-cost-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'subscription-cost-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'overtime-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'take-home-pay-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'wedding-budget-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'amortization-table-generator': ['compound-interest-calculator', 'loan-calculator', 'annuity-calculator', 'apy-calculator'],
  'heart-rate-zone-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'caffeine-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'steps-to-calories-calculator': ['tdee-calculator', 'bmi-calculator', 'bmr-calculator', 'body-fat-calculator'],
  'paint-calculator': ['loan-calculator', 'compound-interest-calculator', 'json-formatter', 'jwt-decoder'],
  'dog-age-calculator': ['loan-calculator', 'compound-interest-calculator', 'json-formatter', 'jwt-decoder'],
  'keycode-info': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'mime-type-lookup': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'xml-formatter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'markdown-toc-generator': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'log-filter-tool': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'ascii-table': ['json-formatter', 'jwt-decoder', 'base-converter', 'base64-decoder'],
  'screen-time-calculator': ['cron-parser', 'age-calculator', 'age-difference-calculator', 'date-difference-calculator'],
  'reading-level-checker': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'hmac-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'password-entropy-checker'],
  'jwt-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'hash-comparator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hmac-generator', 'password-entropy-checker'],
  'base-converter': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base64-decoder'],
  'cron-expression-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'htaccess-redirect-generator': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'unicode-character-lookup': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'toml-to-json': ['json-formatter', 'jwt-decoder', 'ascii-table', 'base-converter'],
  'dice-roller': ['coin-flip', 'random-team-generator', 'wheel-spinner', 'loan-calculator'],
  'coin-flip': ['dice-roller', 'random-team-generator', 'wheel-spinner', 'loan-calculator'],
  'wheel-spinner': ['coin-flip', 'dice-roller', 'random-team-generator', 'loan-calculator'],
  'morse-code-translator': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'typing-speed-test': ['word-counter', 'add-line-numbers', 'character-frequency', 'csv-to-markdown-table'],
  'random-team-generator': ['coin-flip', 'dice-roller', 'wheel-spinner', 'loan-calculator'],
  'password-entropy-checker': ['aes-encrypt-decrypt', 'bcrypt-hash-generator', 'hash-comparator', 'hmac-generator'],
  'llm-cost-calculator': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'context-window-checker': ['csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter', 'json-repair'],
  'json-to-zod': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'aes-encrypt-decrypt': ['bcrypt-hash-generator', 'hash-comparator', 'hmac-generator', 'password-entropy-checker'],
  'car-cost-calculator': ['compound-interest-calculator', 'loan-calculator', 'amortization-table-generator', 'annuity-calculator'],
  'json-repair': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'markdown-fence-extractor': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'prompt-template-filler': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'openai-tools-builder': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'csv-to-finetune-jsonl': ['context-window-checker', 'embedding-price-calculator', 'gpt-token-counter', 'json-repair'],
  'token-visualizer': ['context-window-checker', 'csv-to-finetune-jsonl', 'embedding-price-calculator', 'gpt-token-counter'],
  'embedding-price-calculator': ['context-window-checker', 'csv-to-finetune-jsonl', 'gpt-token-counter', 'json-repair'],
}

/** slug → 工作流下一步推荐(显式 nextTools 优先,否则同分类前 2 款) */
export const nextIndex: Record<string, string[]> = {
  'loan-calculator': ['amortization-table-generator', 'mortgage-calculator'],
  'mortgage-calculator': ['amortization-table-generator', 'down-payment-calculator'],
  'compound-interest-calculator': ['loan-calculator', 'amortization-table-generator'],
  'apy-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'roi-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'credit-card-minimum-payment-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'cash-back-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'down-payment-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'dti-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'commission-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'bill-split-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'savings-goal-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'net-worth-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'annuity-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'capital-gains-tax-estimator': ['compound-interest-calculator', 'loan-calculator'],
  'rent-vs-buy-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'inflation-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'retirement-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'simple-interest-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'unit-price-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'markup-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'hourly-to-salary-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'credit-card-payoff-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'income-tax-estimator': ['compound-interest-calculator', 'loan-calculator'],
  'salary-converter': ['compound-interest-calculator', 'loan-calculator'],
  'sales-tax-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'tip-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'discount-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'json-formatter': ['json-to-typescript', 'json-diff'],
  'jwt-decoder': ['json-formatter', 'ascii-table'],
  'base64-encoder': ['json-formatter', 'jwt-decoder'],
  'base64-decoder': ['json-formatter', 'jwt-decoder'],
  'regex-tester': ['json-formatter', 'jwt-decoder'],
  'uuid-generator': ['json-formatter', 'jwt-decoder'],
  'curl-converter': ['json-formatter', 'jwt-decoder'],
  'markdown-to-html': ['json-formatter', 'jwt-decoder'],
  'hash-generator': ['json-formatter', 'jwt-decoder'],
  'binary-to-text': ['json-formatter', 'jwt-decoder'],
  'text-to-binary': ['json-formatter', 'jwt-decoder'],
  'url-query-parser': ['json-formatter', 'jwt-decoder'],
  'text-size-estimator': ['json-formatter', 'jwt-decoder'],
  'json-minifier': ['json-formatter', 'jwt-decoder'],
  'csv-to-json': ['json-formatter', 'jwt-decoder'],
  'json-to-csv': ['json-formatter', 'jwt-decoder'],
  'lorem-ipsum-generator': ['json-formatter', 'jwt-decoder'],
  'random-number-generator': ['json-formatter', 'jwt-decoder'],
  'html-escape': ['json-formatter', 'jwt-decoder'],
  'html-unescape': ['json-formatter', 'jwt-decoder'],
  'url-encoder': ['json-formatter', 'jwt-decoder'],
  'url-decoder': ['json-formatter', 'jwt-decoder'],
  'slug-generator': ['json-formatter', 'jwt-decoder'],
  'json-to-typescript': ['json-formatter', 'jwt-decoder'],
  'yaml-to-json': ['json-formatter', 'jwt-decoder'],
  'sql-formatter': ['json-formatter', 'jwt-decoder'],
  'image-to-base64': ['json-formatter', 'jwt-decoder'],
  'word-counter': ['add-line-numbers', 'character-frequency'],
  'text-diff': ['word-counter', 'add-line-numbers'],
  'remove-line-breaks': ['word-counter', 'add-line-numbers'],
  'find-and-replace': ['word-counter', 'add-line-numbers'],
  'uppercase-converter': ['word-counter', 'add-line-numbers'],
  'lowercase-converter': ['word-counter', 'add-line-numbers'],
  'title-case-converter': ['word-counter', 'add-line-numbers'],
  'sentence-case-converter': ['word-counter', 'add-line-numbers'],
  'slug-to-title': ['word-counter', 'add-line-numbers'],
  'html-tag-stripper': ['word-counter', 'add-line-numbers'],
  'character-frequency': ['word-counter', 'add-line-numbers'],
  'email-extractor': ['word-counter', 'add-line-numbers'],
  'url-extractor': ['word-counter', 'add-line-numbers'],
  'add-line-numbers': ['word-counter', 'character-frequency'],
  'text-to-list': ['word-counter', 'add-line-numbers'],
  'reverse-text': ['word-counter', 'add-line-numbers'],
  'remove-duplicate-lines': ['word-counter', 'add-line-numbers'],
  'sort-lines': ['word-counter', 'add-line-numbers'],
  'whitespace-remover': ['word-counter', 'add-line-numbers'],
  'list-diff': ['word-counter', 'add-line-numbers'],
  'mass-converter': ['angle-converter', 'area-converter'],
  'density-converter': ['angle-converter', 'area-converter'],
  'power-converter': ['angle-converter', 'area-converter'],
  'flow-rate-converter': ['angle-converter', 'area-converter'],
  'data-storage-converter': ['angle-converter', 'area-converter'],
  'time-converter': ['angle-converter', 'area-converter'],
  'numeral-system-converter': ['angle-converter', 'area-converter'],
  'angle-converter': ['area-converter', 'cooking-converter'],
  'fuel-economy-converter': ['angle-converter', 'area-converter'],
  'pressure-converter': ['angle-converter', 'area-converter'],
  'energy-converter': ['angle-converter', 'area-converter'],
  'frequency-converter': ['angle-converter', 'area-converter'],
  'weight-converter': ['angle-converter', 'area-converter'],
  'temperature-converter': ['angle-converter', 'area-converter'],
  'speed-converter': ['angle-converter', 'area-converter'],
  'area-converter': ['angle-converter', 'cooking-converter'],
  'volume-converter': ['angle-converter', 'area-converter'],
  'length-converter': ['angle-converter', 'area-converter'],
  'trapezoid-calculator': ['percentage-calculator', 'average-calculator'],
  'cube-calculator': ['percentage-calculator', 'average-calculator'],
  'sphere-calculator': ['percentage-calculator', 'average-calculator'],
  'scientific-notation-converter': ['percentage-calculator', 'average-calculator'],
  'prime-number-checker': ['percentage-calculator', 'average-calculator'],
  'prime-factorization-calculator': ['percentage-calculator', 'average-calculator'],
  'combination-calculator': ['percentage-calculator', 'average-calculator'],
  'permutation-calculator': ['percentage-calculator', 'average-calculator'],
  'circle-calculator': ['percentage-calculator', 'average-calculator'],
  'triangle-calculator': ['percentage-calculator', 'average-calculator'],
  'rectangle-calculator': ['percentage-calculator', 'average-calculator'],
  'standard-deviation-calculator': ['percentage-calculator', 'average-calculator'],
  'percentile-calculator': ['percentage-calculator', 'average-calculator'],
  'fraction-calculator': ['percentage-calculator', 'average-calculator'],
  'ratio-calculator': ['percentage-calculator', 'average-calculator'],
  'lcm-gcd-calculator': ['percentage-calculator', 'average-calculator'],
  'average-calculator': ['percentage-calculator', 'circle-calculator'],
  'percentage-calculator': ['average-calculator', 'circle-calculator'],
  'bmi-calculator': ['tdee-calculator', 'bmr-calculator'],
  'calorie-calculator': ['tdee-calculator', 'bmi-calculator'],
  'tdee-calculator': ['bmi-calculator', 'bmr-calculator'],
  'bmr-calculator': ['tdee-calculator', 'bmi-calculator'],
  'body-fat-calculator': ['tdee-calculator', 'bmi-calculator'],
  'macro-calculator': ['tdee-calculator', 'bmi-calculator'],
  'pregnancy-due-date-calculator': ['tdee-calculator', 'bmi-calculator'],
  'water-intake-calculator': ['tdee-calculator', 'bmi-calculator'],
  'ideal-weight-calculator': ['tdee-calculator', 'bmi-calculator'],
  'svg-to-image': ['aspect-ratio-calculator', 'color-contrast-checker'],
  'px-to-rem': ['svg-to-image', 'aspect-ratio-calculator'],
  'aspect-ratio-calculator': ['svg-to-image', 'color-contrast-checker'],
  'color-contrast-checker': ['svg-to-image', 'aspect-ratio-calculator'],
  'color-converter': ['svg-to-image', 'aspect-ratio-calculator'],
  'open-graph-generator': ['svg-to-image', 'aspect-ratio-calculator'],
  'css-shadow-generator': ['svg-to-image', 'aspect-ratio-calculator'],
  'favicon-generator': ['svg-to-image', 'aspect-ratio-calculator'],
  'cron-parser': ['age-calculator', 'age-difference-calculator'],
  'age-calculator': ['cron-parser', 'age-difference-calculator'],
  'date-difference-calculator': ['cron-parser', 'age-calculator'],
  'age-difference-calculator': ['cron-parser', 'age-calculator'],
  'grade-calculator': ['final-grade-calculator', 'gpa-calculator'],
  'final-grade-calculator': ['gpa-calculator', 'grade-calculator'],
  'gpa-calculator': ['final-grade-calculator', 'grade-calculator'],
  'password-strength-checker': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'password-generator': ['password-entropy-checker', 'password-strength-checker'],
  'qr-code-generator': ['freelance-invoice-generator', 'saas-ltv-churn-calculator'],
  'gpt-token-counter': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'ip-subnet-calculator': ['json-formatter', 'jwt-decoder'],
  'chmod-calculator': ['json-formatter', 'jwt-decoder'],
  'ssh-key-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'bcrypt-hash-generator': ['aes-encrypt-decrypt', 'hash-comparator'],
  'user-agent-parser': ['json-formatter', 'jwt-decoder'],
  'json-schema-generator': ['json-formatter', 'jwt-decoder'],
  'naming-case-converter': ['json-formatter', 'jwt-decoder'],
  'nginx-config-generator': ['json-formatter', 'jwt-decoder'],
  'webp-to-png-converter': ['svg-to-image', 'aspect-ratio-calculator'],
  'png-to-webp-converter': ['svg-to-image', 'aspect-ratio-calculator'],
  'image-resizer': ['svg-to-image', 'aspect-ratio-calculator'],
  'svg-minifier': ['svg-to-image', 'aspect-ratio-calculator'],
  'css-gradient-generator': ['svg-to-image', 'aspect-ratio-calculator'],
  'css-clamp-calculator': ['svg-to-image', 'aspect-ratio-calculator'],
  'csv-to-markdown-table': ['word-counter', 'add-line-numbers'],
  'text-cleaner': ['word-counter', 'add-line-numbers'],
  'srt-subtitle-shift': ['word-counter', 'add-line-numbers'],
  'code-beautifier': ['json-formatter', 'jwt-decoder'],
  'secret-key-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'auto-loan-calculator': ['car-cost-calculator', 'amortization-table-generator'],
  'ebay-fee-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'saas-ltv-churn-calculator': ['qr-code-generator', 'freelance-invoice-generator'],
  'freelance-invoice-generator': ['qr-code-generator', 'saas-ltv-churn-calculator'],
  'reverse-stripe-fee-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'timezone-converter': ['cron-parser', 'age-calculator'],
  'days-countdown-calculator': ['cron-parser', 'age-calculator'],
  'reading-speaking-time': ['cron-parser', 'age-calculator'],
  'random-choice-picker': ['json-formatter', 'jwt-decoder'],
  'wordle-solver': ['word-counter', 'add-line-numbers'],
  'ip-checker': ['json-formatter', 'jwt-decoder'],
  'epoch-converter': ['json-formatter', 'jwt-decoder'],
  'json-diff': ['json-formatter', 'jwt-decoder'],
  'line-diff-checker': ['word-counter', 'add-line-numbers'],
  'robots-txt-generator': ['json-formatter', 'jwt-decoder'],
  'roman-numeral-converter': ['percentage-calculator', 'average-calculator'],
  'pace-calculator': ['tdee-calculator', 'bmi-calculator'],
  'protein-intake-calculator': ['tdee-calculator', 'bmi-calculator'],
  'electricity-cost-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'sleep-calculator': ['tdee-calculator', 'bmi-calculator'],
  'cooking-converter': ['angle-converter', 'area-converter'],
  'fuel-cost-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'subscription-cost-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'overtime-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'take-home-pay-calculator': ['hourly-to-salary-calculator', 'overtime-calculator'],
  'wedding-budget-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'amortization-table-generator': ['compound-interest-calculator', 'loan-calculator'],
  'heart-rate-zone-calculator': ['tdee-calculator', 'bmi-calculator'],
  'caffeine-calculator': ['tdee-calculator', 'bmi-calculator'],
  'steps-to-calories-calculator': ['tdee-calculator', 'bmi-calculator'],
  'paint-calculator': ['loan-calculator', 'compound-interest-calculator'],
  'dog-age-calculator': ['loan-calculator', 'compound-interest-calculator'],
  'keycode-info': ['json-formatter', 'jwt-decoder'],
  'mime-type-lookup': ['json-formatter', 'jwt-decoder'],
  'xml-formatter': ['json-formatter', 'jwt-decoder'],
  'markdown-toc-generator': ['word-counter', 'add-line-numbers'],
  'log-filter-tool': ['json-formatter', 'jwt-decoder'],
  'ascii-table': ['json-formatter', 'jwt-decoder'],
  'screen-time-calculator': ['cron-parser', 'age-calculator'],
  'reading-level-checker': ['word-counter', 'add-line-numbers'],
  'hmac-generator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'jwt-generator': ['json-formatter', 'jwt-decoder'],
  'hash-comparator': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'base-converter': ['json-formatter', 'jwt-decoder'],
  'cron-expression-generator': ['json-formatter', 'jwt-decoder'],
  'htaccess-redirect-generator': ['json-formatter', 'jwt-decoder'],
  'unicode-character-lookup': ['json-formatter', 'jwt-decoder'],
  'toml-to-json': ['json-formatter', 'jwt-decoder'],
  'dice-roller': ['coin-flip', 'random-team-generator'],
  'coin-flip': ['dice-roller', 'random-team-generator'],
  'wheel-spinner': ['coin-flip', 'dice-roller'],
  'morse-code-translator': ['word-counter', 'add-line-numbers'],
  'typing-speed-test': ['word-counter', 'add-line-numbers'],
  'random-team-generator': ['coin-flip', 'dice-roller'],
  'password-entropy-checker': ['aes-encrypt-decrypt', 'bcrypt-hash-generator'],
  'llm-cost-calculator': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'context-window-checker': ['csv-to-finetune-jsonl', 'embedding-price-calculator'],
  'json-to-zod': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'aes-encrypt-decrypt': ['bcrypt-hash-generator', 'hash-comparator'],
  'car-cost-calculator': ['compound-interest-calculator', 'loan-calculator'],
  'json-repair': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'markdown-fence-extractor': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'prompt-template-filler': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'openai-tools-builder': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'csv-to-finetune-jsonl': ['context-window-checker', 'embedding-price-calculator'],
  'token-visualizer': ['context-window-checker', 'csv-to-finetune-jsonl'],
  'embedding-price-calculator': ['context-window-checker', 'csv-to-finetune-jsonl'],
}

/** 取某工具的相关工具轻量数据(缺失/未知 slug 一律安全回退空数组) */
export function getRelatedToolsLite(slug: string, limit = 4): ToolLiteMeta[] {
  return (relatedIndex[slug] ?? [])
    .slice(0, limit)
    .map((s) => toolLiteMeta[s])
    .filter(Boolean)
}

/** 取某工具的工作流下一步轻量数据(缺失回退空数组) */
export function getNextToolsLite(slug: string): ToolLiteMeta[] {
  return (nextIndex[slug] ?? [])
    .map((s) => toolLiteMeta[s])
    .filter(Boolean)
}
