/**
 * Wordle 词典 —— 常用英文 5 字母词表(纯数据,无逻辑)
 * 单个模板字符串按空白切分;全小写;复数/常见变形均收录。
 */
const WORDS = `
aback abate abbey abbot abhor abide abode abort about above abuse acorn acrid actor acute adage adapt adder adept admin admit adobe adopt adore adorn adult aegis affix afire afoot afoul after again agape agate agent agile aging aglow agony agree ahead aided aider aisle alarm album alder alert algae alibi alien align alike alive allay alley allot allow alloy aloft alone along aloof aloud alpha altar alter amass amaze amber amble amend amigo amino amiss among amour ample amply amuse angel anger angle angry angst anime ankle annex annoy anode antic anvil aorta apart aphid apish apnea apple apply apron aptly arbor ardor arena argue arise armor aroma arose array arrow arson artsy ascot ashen ashes aside asked askew asset atlas atoll attic audio audit augur aunty avail avert avian avoid await awake award aware awash awful awoke axiom azure
bacon badge badly bagel baggy baker balmy banal banjo barge baron basal basic basil basin basis baste batch bathe baton batty bayou beach beard beast beech beefy befit began begin begun beige being belch belie belly below bench berth beset bezel bicep biddy bigot bilge billy binge bingo biome birch birth bison black blade blame bland blank blare blast blaze bleak bleed blend bless blind blink bliss blitz bloat block bloke blond blood bloom blown blues bluff blunt blurb blurt blush board boast bobby bonus boost booth booze boozy borax borne bosom bossy botch bough bound bowel boxer brace braid brain brake brand brash brass brave bravo brawl brawn bread break breed briar bribe brick bride brief brine bring brink briny brisk broad broil broke brood brook broom broth brown brunt brush brute buddy budge buggy build built bulge bulky bully bunch bunny burly burnt burst bushy busty butte buyer bylaw
cabal cabin cable cacao cache cacti cadet cagey cairn camel cameo canal candy canoe canon caper carat cargo carol carry carve caste catch cater catty caulk cause cease cedar cello chalk champ chant chaos chard charm chart chase chasm cheap cheat check cheek cheer chess chest chick chide chief child chili chill chime chimp china chirp chive choir choke chord chore chose chuck chunk churn chute cider cigar cinch circa civic civil claim clamp clang clank clash clasp class clean clear cleat cleft clerk click cliff climb cling clink cloak clock clone close cloth cloud clout clove clown cluck clump coach coast cobra cocoa colon color comet comfy comic comma conch condo copse coral corny couch cough could count coupe court coven cover covet cower coyly crack craft cramp crane crank crash crass crate crave crawl craze crazy creak cream credo creed creek crepe crept crest cried crier crime crimp crisp croak crock crone crony crook cross croup crowd crown crude cruel crumb crush crust crypt cubic cumin curio curly curry curse curve cushy cuter cycle cynic
daddy daily dairy daisy dance dandy datum daunt dealt death debit debug debut decal decay decor decoy decry defer deign deity delay delta delve demon demur denim dense depot depth derby deter detox deuce devil diary dicey digit dilly dimly diner dingo dingy diode dirge dirty disco ditch ditto ditty diver dodge dogma doing dolly donor donut doubt dough douse dowdy dowel dozen draft drain drake drama drank drape drawl drawn dread dream dress dried drier drift drill drink drive droll drone drool droop drops drove drown druid drunk dryer dryly duchy dully dummy dusty dutch dwarf dwell dwelt dying
eager eagle early earth easel eaten eater ebony eclat edict edify eerie eight eject elate elbow elder elect elegy elite elope elude elves email embed ember emend emery empty enact ended endow ennui ensue enter entry envoy epoch epoxy equal equip erase erect erode error erupt essay ester ether ethic ethos evade event every evict evoke exact exalt excel exert exile exist expel extra exult eying
fable facet faint fairy faith false fancy farce fatal fatty fault fauna favor feast fecal feign fella felon femme femur fence feral ferry fetal fetch fetid fetus fever fewer fiber ficus field fiend fiery fifty fight filer filth final finch finer first fishy fjord flair flake flaky flame flank flare flash flask fleck fleet flesh flick flier fling flint flirt float flock flood floor flora floss flour flout flown fluff fluid fluke flume flung flush flute flyer foamy focal focus foggy foist folio folly foray force forge forgo forte forth forty forum found foyer frail frame frank fraud freak freed fresh friar fried frill frisk frock front frost froth frown froze fruit fudge fugue fully fungi funky funny furor furry fuzzy
gamer gamma gamut gassy gauge gaunt gauze gavel gawky gecko geeky genie genre ghost ghoul giant giddy given giver glade gland glare glass glaze gleam glean glide glint gloat globe gloom glory gloss glove glyph gnash gnome goody gooey goofy goose gorge gouge gourd grace grade grain grand grant grape graph grasp grass grate grave gravy graze great greed green greet grief grill grimy grind gripe groan groin groom grope gross group grove growl grown gruff grunt guard guess guest guide guild guilt guise gulch gully gumbo gummy gushy gusty gypsy
habit hairy halve handy happy hardy harem harpy harry harsh haste hasty hatch hater haunt haven havoc hazel heady heard heart heath heave heavy hedge hefty heist helix hello hence heron hilly hinge hippo hitch hoard hobby hoist holly homer honey honor horde horny horse hotel hotly hound house hover howdy human humid humor hunch hurry husky hutch hydro hyena
icily icing ideal idiom idiot idler idyll igloo image imbue impel imply inane inbox incur index inept inert infer ingot inlet inner input inset inter intro ionic irate irony issue itchy ivory
jaunt jazzy jewel jiffy joint joist joker jolly joust judge juice juicy jumbo jumpy juror
karma kayak kebab kempt khaki kiosk kitty knack knave knead kneel knelt knife knock knoll known koala krill
label labor laden ladle lager lance lapel lapse large larva latch later lathe laugh layer leach leafy leaky leant learn lease leash least leave ledge leech leery lefty legal leggy lemon lemur leper level lever libel liege light liken lilac limbo limit linen liner lipid lithe liver livid llama loamy lobby local locus lodge lofty logic login loopy loose lorry loser louse lousy lover lower lowly loyal lucid lucky lunar lunch lunge lupus lurch lurid lusty lying lymph lyric
macaw macho macro madam madly magic magma maize major maker mambo mamma manga mange mango mangy manic manor maple march marry marsh mason match matey matte maxim maybe mayor mealy meant meaty mecca medal media medic melon mercy merge merit merry metal meter metro micro midst might mimic mince miner minim minor minty minus mirth miser misty mixer modal model modem mogul moist molar moldy money month moody moose moral moron morph mossy motel motif motor motto mound mount mourn mouse mouth mover movie mower mucky mucus muddy mulch mummy munch mural murky mushy music musky musty muted myrrh
nadir naive nanny nasal nasty natal naval navel needy neigh nerdy nerve never newer newly nicer niche niece night ninja ninth noble nobly noise noisy nomad north nosey notch novel nudge nurse nutty nylon nymph
oaken obese occur ocean octal octet odder oddly offal offer often olden older olive omega onion onset opera opine opium optic orbit order organ other otter ought ounce outdo outer outgo ovary ovate overt owner oxide ozone
pagan paint panel panic pansy papal paper parka parry parse party pasta paste pasty patch patio pause peach pearl pecan pedal penal penny perch peril perky petty phase phone photo piano piece piety piggy pilot pinch piney pinky pinto piper pique pitch pithy pivot pixel pixie pizza place plaid plain plait plane plank plant plate plaza plead pleat pluck plumb plume plump plunk plush point poise poker polar polka polyp pouch pound pouty power prank prawn preen press price prick pride pried prima prime print prior prism privy prize probe prone prong proof prose proud prove prowl proxy prune psalm pubic pudgy puffy pulpy pulse punch pupil puppy puree purer purge purse pushy putty pygmy
quack quail quake qualm quark quart quash quasi queen queer quell query quest queue quick quiet quill quilt quirk quite quota quote quoth
rabbi rabid racer radar radio rainy raise rajah rally ranch range rapid rarer raspy ratio ratty raven rayon razor reach react ready realm rearm rebel rebus rebut recap recur reedy refer refit regal rehab reign relax relay relic remit renal renew repay repel reply rerun reset resin retch retro retry reuse revel revue rhino rhyme rider ridge rifle right rigid rigor rinse ripen risen riser risky rival river rivet roach roast robin robot rocky rodeo rogue roomy roost rotor rough round rouse route rover rowdy royal ruddy ruler rumba rumor rupee rural rusty
sadly safer saint salad sally salon salsa salty salve salvo sandy saner sappy sassy satin satyr sauce saucy sauna savor savvy scald scale scalp scaly scamp scant scare scarf scary scene scent scion scoff scold scone scoop scope score scorn scour scout scowl scram scrap screw scrub scrum scuba sedan seedy segue seine seize sense sepia serif serum serve setup seven sever sewer shack shade shady shaft shake shall shame shank shape shard share shark sharp shave shawl shear sheen sheep sheer sheet shelf shell shied shift shine shiny shirt shoal shock shone shook shoot shore shorn short shout shove shown showy shred shrew shrub shrug shuck shunt shush shyly siege sieve sight sigma silky silly since sinew singe siren sitar sixth sixty skate skier skiff skill skimp skirt skulk skull skunk slack slain slang slant slash slate slave sleek sleep sleet slept slice slick slide slime slimy sling slink sloop slope slosh sloth slump slung slunk slurp slush slyly smack small smart smash smear smell smelt smile smirk smith smock smoke smoky smote snack snail snake snaky snare snarl sneak sneer snide sniff snipe snore snort snout snowy snuff soapy sober soggy solar solid solve sonar sonic sooth sooty sorry sound south space spade spank spare spark spasm spawn speak spear speck speed spell spelt spend spent sperm spice spicy spied spiel spike spill spilt spine spiny spire spite split spoil spoke spoof spook spool spoon spore sport spout spray spree sprig spunk spurn spurt squad squat squid stack staff stage staid stain stair stake stale stalk stall stamp stand stare stark start stash state stave stead steak steal steam steed steel steep steer stern stick stiff still stilt sting stink stint stock stoic stole stomp stone stony stood stool stoop store storm story stout stove strap straw stray strip strut stuck study stuff stump stung stunk stunt style suave sugar suing suite sulky sully sumac sunny super surge surly sushi swami swamp swarm swash swath swear sweat sweep sweet swell swept swift swill swine swing swirl swish swoon swoop sword swore sworn swung syrup
tabby table tacit tacky taffy taint taken taker tally talon tamer tango tangy taper tapir tardy tarot taste tasty tatty taunt tawny teach teary tease teddy teeth tempo tenet tenor tense tenth tepee tepid terra terse testy thank theft their theme there these theta thick thief thigh thing think third thong thorn those three threw throb throw thumb thump thyme tiara tibia tidal tiger tight tilde timer timid tipsy titan tithe title toast today token tonal tonga tonic tooth topaz topic torch torso torus total totem touch tough towel tower toxic toxin trace track tract trade trail train trait tramp trash trawl tread treat trend triad trial tribe trice trick tried trill tripe trite troll troop trope trout trove truce truck truly trump trunk truss trust truth tuber tulip tulle tumor tuner tunic tutor tweed tweet twice twine twist tying
udder ulcer ultra umbra uncle under undid undue unfed unfit unify union unite unity unlit unmet unset untie until unwed unzip upper upset urban urine usage usher using usual usurp utile utter
vague valet valid valor value valve vapor vault vaunt vegan venom venue verge verse verve vicar video vigil vigor villa vinyl viola viper viral virus visit visor vista vital vivid vixen vocal vodka vogue voice vomit voter vouch vowel
wacky wafer wager wagon waist waive waltz warty washy watch water waver waxen weary weave wedge weedy weigh weird welsh whack whale wharf wheat wheel whelp where which whiff while whine whiny whirl whisk white whole whoop widen wider widow width wield wight wimpy wince winch windy wiper wired wiser wispy witch witty wives woken woman women woody wooly woozy wordy world worry worse worst worth would wound woven wrack wrath wreak wreck wrest wring wrist write wrong wrote wrung wryly
yacht yearn yeast yield yodel yogic yokel young yours youth yummy
zebra zesty zonal
`

export const FIVE_LETTER_WORDS: string[] = WORDS.split(/\s+/).filter(Boolean)
