import type { ReactNode } from 'react'
import { ToolContent } from '@/lib/content-templates'

/** 8 个开发者工具的原创内容 */

export function RandomNumberGeneratorContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          This tool generates random numbers within any range you specify. Use it for picking
          lottery numbers, selecting contest winners, choosing a random student, running
          simulations, or any time you need an unbiased random selection.
        </p>
      }
      sections={[
        {
          heading: 'How It Works',
          body: (
            <p>
              This generator uses JavaScript&apos;s built-in pseudo-random number generator
              (PRNG), which produces numbers uniformly distributed across your chosen range. The
              &quot;unique numbers&quot; option ensures no repeats — useful for raffles and
              sampling without replacement.
            </p>
          ),
        },
        {
          heading: 'True Random vs. Pseudo-Random',
          body: (
            <p>
              Most software (including this tool) uses <strong>pseudo-random</strong> numbers,
              generated by mathematical algorithms. These are sufficient for games, simulations,
              and everyday use, but predictable in principle. For cryptography or high-stakes
              lotteries, &quot;true&quot; random numbers from physical sources (radioactive decay,
              atmospheric noise) are needed — see Random.org for that.
            </p>
          ),
        },
        {
          heading: 'Common Uses',
          body: (
            <ul>
              <li>Pick a contest or raffle winner fairly</li>
              <li>Generate lottery number combinations</li>
              <li>Randomize student or team selection</li>
              <li>Run Monte Carlo simulations</li>
              <li>Test code with random inputs</li>
              <li>Roll virtual dice (set min 1, max 6)</li>
            </ul>
          ),
        },
      ]}
      faqs={[
        { q: 'Can this be used for a real lottery or gambling?', a: 'For casual use, yes. For regulated gambling or official lotteries, you need certified hardware RNGs. This tool is fine for office raffles, classroom picks, and simulations.' },
      ]}
    />
  )
}

export function PasswordStrengthCheckerContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          This tool analyzes your password&apos;s strength in real time and shows the estimated
          entropy, a strength rating, and a checklist of what would make it stronger. Everything
          runs in your browser — your password is never transmitted or stored.
        </p>
      }
      sections={[
        {
          heading: 'How Strength Is Measured',
          body: (
            <p>
              Strength is based on <strong>entropy</strong> — the number of possible combinations
              an attacker would need to try. Longer passwords with more character types have higher
              entropy. A 12-character password using all four types (upper, lower, numbers,
              symbols) has about 78 bits of entropy, which is effectively uncrackable.
            </p>
          ),
        },
        {
          heading: 'Strength Levels',
          body: (
            <ul>
              <li><strong>Very Weak (&lt;40 bits):</strong> Crackable in seconds. Never use.</li>
              <li><strong>Weak (40-60 bits):</strong> Hours to days to crack.</li>
              <li><strong>Strong (60-80 bits):</strong> Years to crack. Good for most accounts.</li>
              <li><strong>Very Strong (&gt;80 bits):</strong> Uncrackable. Use for email, banking, password managers.</li>
            </ul>
          ),
        },
        {
          heading: 'Why Length Matters Most',
          body: (
            <p>
              Adding length increases entropy exponentially, while adding character types increases
              it linearly. A 16-character lowercase password (75 bits) is stronger than an 8-character
              password using all four types (52 bits). When in doubt, go longer.
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Is it safe to type my real password here?', a: 'Yes. This tool processes everything locally in your browser. There is no network request — your password never leaves your device. You can also test variations.' },
        { q: 'What if my password is in a data breach?', a: 'Strength only measures guessability, not whether it has been leaked. Check Have I Been Pwned to see if your password has appeared in known breaches.' },
      ]}
    />
  )
}

export function Base64EncoderContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          Base64 encodes binary data as ASCII text so it can travel through systems designed for
          text — email, JSON, HTML, URLs. This tool encodes any text to Base64, with proper UTF-8
          support for non-English characters and emoji.
        </p>
      }
      sections={[
        {
          heading: 'What Base64 Is Used For',
          body: (
            <ul>
              <li><strong>Email attachments</strong> (MIME encoding)</li>
              <li><strong>Data URIs</strong> — embedding images directly in HTML/CSS</li>
              <li><strong>APIs</strong> — sending binary data in JSON</li>
              <li><strong>JWT tokens</strong> for authentication</li>
              <li><strong>Storing binary in text-based formats</strong></li>
            </ul>
          ),
        },
        {
          heading: 'Base64 Is NOT Encryption',
          body: (
            <p>
              Base64 is an <em>encoding</em>, not encryption. Anyone can decode it instantly — it
              provides zero security. Never use Base64 to protect sensitive data. Use it only for
              transport compatibility, then apply real encryption (AES, etc.) separately.
            </p>
          ),
        },
        {
          heading: 'The Size Cost',
          body: (
            <p>
              Base64 output is about <strong>33% larger</strong> than the input. Every 3 bytes
              becomes 4 characters. This is the trade-off for text-safe transport.
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Why does my non-English text look wrong?', a: 'This tool uses proper UTF-8 handling, so accented letters and emoji encode correctly. If you see mojibake, the decoder you\'re using probably assumes a different character encoding.' },
      ]}
    />
  )
}

export function Base64DecoderContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          This tool decodes Base64 back to readable text. Paste any valid Base64 string to recover
          the original content. Handles UTF-8 properly for international text.
        </p>
      }
      sections={[
        {
          heading: 'Common Decode Scenarios',
          body: (
            <ul>
              <li>Decode JWT tokens to inspect their payload</li>
              <li>Read data URIs from HTML or CSS</li>
              <li>Debug API responses that contain Base64</li>
              <li>Recover text from email attachments</li>
              <li>Inspect HTTP Basic Auth headers</li>
            </ul>
          ),
        },
        {
          heading: 'When Decoding Fails',
          body: (
            <p>
              If you see an error, the input is likely not valid Base64. Common causes: missing
              padding (=), stray whitespace, or characters outside the Base64 alphabet
              (A-Z, a-z, 0-9, +, /).
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Can I decode images or files?', a: 'This tool decodes to text only. For binary data like images, the output may look garbled because it\'s binary bytes interpreted as text. Use a dedicated Base64-to-file converter for binary content.' },
      ]}
    />
  )
}

export function HTMLEscapeContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          HTML escaping converts special characters (<code>&amp; &lt; &gt; &quot;</code>) into
          their entity equivalents (<code>&amp;amp; &amp;lt; &amp;gt;</code>), so they display
          correctly in a browser and prevent XSS attacks.
        </p>
      }
      sections={[
        {
          heading: 'Why Escaping Matters',
          body: (
            <p>
              If user input contains <code>&lt;script&gt;</code> and you insert it into a page
              without escaping, the browser runs the script — a classic XSS (cross-site scripting)
              attack. Escaping turns it into harmless text that displays as <code>&lt;script&gt;</code>
              instead of executing.
            </p>
          ),
        },
        {
          heading: 'What Gets Escaped',
          body: (
            <ul>
              <li><code>&amp;</code> → <code>&amp;amp;</code> (must be escaped first)</li>
              <li><code>&lt;</code> → <code>&amp;lt;</code></li>
              <li><code>&gt;</code> → <code>&amp;gt;</code></li>
              <li><code>&quot;</code> → <code>&amp;quot;</code></li>
              <li><code>&#39;</code> → <code>&amp;#39;</code></li>
            </ul>
          ),
        },
        {
          heading: 'Escaping for Different Contexts',
          body: (
            <p>
              Escaping rules differ by where text will appear. HTML body escaping (this tool) is
              different from attribute escaping, URL escaping, or JavaScript string escaping. Always
              escape for the specific context — using the wrong one can leave vulnerabilities.
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Is this enough to prevent all XSS?', a: 'HTML body escaping covers the most common case, but XSS has many variants (attribute-based, script-based, URL-based). Use a reputable library like DOMPurify for untrusted HTML.' },
      ]}
    />
  )
}

export function HTMLUnescapeContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          This tool reverses HTML entities back to their original characters — turning{' '}
          <code>&amp;amp;</code> into <code>&amp;</code>, <code>&amp;lt;</code> into{' '}
          <code>&lt;</code>, and so on. Useful for reading escaped content or cleaning up imported
          data.
        </p>
      }
      sections={[
        {
          heading: 'When You\'ll Need This',
          body: (
            <ul>
              <li>Cleaning up content scraped from websites</li>
              <li>Reading escaped text from databases or APIs</li>
              <li>Decoding content from CMS exports</li>
              <li>Fixing double-escaped text (a common bug)</li>
            </ul>
          ),
        },
        {
          heading: 'Named vs. Numeric Entities',
          body: (
            <p>
              HTML entities come in two forms: named (<code>&amp;amp;</code>) and numeric
              (<code>&amp;#38;</code>). This tool handles both, plus hexadecimal numeric entities
              (<code>&amp;#x26;</code>).
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Is unescaping safe?', a: 'This tool uses a detached textarea element, which decodes entities without executing any HTML. The output is plain text, so it cannot trigger scripts.' },
      ]}
    />
  )
}

export function URLencoderContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          URL encoding (also called <strong>percent encoding</strong>) converts special characters
          into a format that&apos;s safe to include in a URL. Spaces become <code>%20</code>,{' '}
          <code>&amp;</code> becomes <code>%26</code>, and so on.
        </p>
      }
      sections={[
        {
          heading: 'Why URLs Need Encoding',
          body: (
            <p>
              URLs can only contain a limited set of characters safely. Characters like spaces,
              quotes, <code>&amp;</code>, <code>=</code>, and non-ASCII letters have special meaning
              or aren&apos;t allowed, so they must be encoded to travel through the web reliably.
            </p>
          ),
        },
        {
          heading: 'Common Encodings',
          body: (
            <ul>
              <li>Space → <code>%20</code> (or <code>+</code> in query strings)</li>
              <li><code>&amp;</code> → <code>%26</code></li>
              <li><code>=</code> → <code>%3D</code></li>
              <li><code>?</code> → <code>%3F</code></li>
              <li><code>/</code> → <code>%2F</code></li>
              <li>中文 → <code>%E4%B8%AD%E6%96%87</code> (UTF-8 bytes)</li>
            </ul>
          ),
        },
        {
          heading: 'encodeURI vs. encodeURIComponent',
          body: (
            <p>
              JavaScript has two functions. <code>encodeURI</code> preserves URL-structure
              characters (<code>/ ? &amp; =</code>) for whole URLs. <code>encodeURIComponent</code>
              encodes everything, for query parameter values. This tool uses the latter, which is
              what you usually want.
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'Should I encode the whole URL or just parameters?', a: 'Encode individual parameter values, not the whole URL. Encoding the whole URL would break the /, ?, and & that define its structure.' },
      ]}
    />
  )
}

export function URLdecoderContent(): ReactNode {
  return (
    <ToolContent
      intro={
        <p>
          This tool decodes percent-encoded URLs back to readable text. Paste any URL-encoded
          string to recover the original characters, including spaces, symbols, and international
          text.
        </p>
      }
      sections={[
        {
          heading: 'When You\'ll Need This',
          body: (
            <ul>
              <li>Reading encoded URLs from server logs</li>
              <li>Decoding query parameters in analytics data</li>
              <li>Cleaning up scraped or exported URLs</li>
              <li>Debugging URL handling in code</li>
            </ul>
          ),
        },
        {
          heading: 'Double Encoding',
          body: (
            <p>
              Sometimes URLs get encoded twice by accident — a space becomes <code>%2520</code>{' '}
              instead of <code>%20</code>. If decoded text still contains <code>%</code> sequences,
              run it through this tool again to fully decode.
            </p>
          ),
        },
      ]}
      faqs={[
        { q: 'What about + for spaces?', a: 'In query strings, + often represents a space (form encoding). This tool uses standard percent decoding, which leaves + as +. Convert + to spaces manually if needed.' },
      ]}
    />
  )
}
