'use client'

import { useState, useMemo, useCallback } from 'react'
import { CalculatorField, ResultCard, CalculatorNote } from '../calculator/CalculatorField'
import { ResultActions } from '../ResultActions'
import { LoadSampleButton } from '../LoadSampleButton'
import { fmtNum, toNum } from '@/lib/format'
import { getConverterSample, type ConverterSample } from '@/lib/tool-samples'
import { useApp } from '@/components/providers/AppProviders'
import { tui, tuiUc } from '@/lib/i18n/tool-l10n'

/**
 * 通用单位转换器工厂
 *
 * 所有线性单位转换(长度、重量、速度、面积、体积等)共用同一套逻辑:
 * value × fromFactor = 基准单位 → 基准单位 ÷ toFactor = 目标值
 *
 * 用法:
 *   export const WeightConverter = makeUnitConverter({
 *     baseUnit: 'kg',
 *     units: { kg: {label:'kg', factor:1}, lb:{...} },
 *     note: '...',
 *   })
 */
export interface UnitDef {
  label: string
  /** 相对基准单位的换算系数(线性单位用,如 1 kg = 1000 g → factor 1000) */
  factor: number
  /**
   * 自定义"转到基准单位"函数(可选)。覆盖 factor,用于非线性换算。
   * 例:燃油经济性 L/100km 与 mpg 是倒数关系,toBase = 235.215 / x。
   * 不提供则回退到 value × factor。
   */
  toBase?: (v: number) => number
  /**
   * 自定义"从基准单位转出"函数(可选)。覆盖 factor。
   * 不提供则回退到 base / factor。
   */
  fromBase?: (b: number) => number
}

export function makeUnitConverter(config: {
  units: Record<string, UnitDef>
  note?: string
  defaultValue?: string
  defaultFrom?: string
  defaultTo?: string
  /** 结果保留小数位 */
  digits?: number
  /** 工具 slug(可选)。用于「Load Sample」时自动从 lib/tool-samples.ts 取示例 */
  slug?: string
  /** 内嵌示例数据(可选);slug 注册表优先,本字段作回退 */
  sample?: ConverterSample
}) {
  const unitKeys = Object.keys(config.units)
  const digits = config.digits ?? 6

  return function UnitConverter() {
    const { locale } = useApp()
    // slug 未设 → tui 返回 fallback(英文原值),行为与改造前一致。
    const slug = config.slug ?? ''
    const L = (key: string, fb: string) => tui(slug, locale, key, fb)
    const LC = (key: string, fb: string) => tuiUc(key, locale, fb)
    const [value, setValue] = useState(config.defaultValue ?? '1')
    const [from, setFrom] = useState(config.defaultFrom ?? unitKeys[0])
    const [to, setTo] = useState(config.defaultTo ?? unitKeys[1] ?? unitKeys[0])

    const result = useMemo(() => {
      const v = toNum(value)
      const fromDef = config.units[from]
      const toDef = config.units[to]
      if (!fromDef || !toDef) return NaN
      // 转到基准单位:value → base
      // 有自定义 toBase(非线性,如燃油经济性倒数)则用之,否则线性 value × factor
      const toBase = (def: UnitDef, val: number): number =>
        def.toBase ? def.toBase(val) : val * def.factor
      // 从基准单位转出:base → target
      // 有自定义 fromBase 则用之;否则线性 base / factor
      const fromBase = (def: UnitDef, base: number): number =>
        def.fromBase ? def.fromBase(base) : base / def.factor
      const baseVal = toBase(fromDef, v)
      return fromBase(toDef, baseVal)
    }, [value, from, to])

    const options = unitKeys.map((k) => ({ label: L(`unit.${k}`, config.units[k].label), value: k }))

    // 示例数据:优先 lib/tool-samples.ts 注册表(按 slug),否则用 config.sample。
    const sample = config.slug ? (getConverterSample(config.slug) ?? config.sample) : config.sample

    const handleLoadSample = useCallback(() => {
      if (!sample) return
      setValue(sample.value)
      setFrom(sample.from)
      setTo(sample.to)
    }, [sample])

    // 单位 label(回退到 key),供摘要/公式/结果卡显示,避免暴露 raw key 如 'gb'
    const fromLabel = L(`unit.${from}`, config.units[from]?.label ?? from)
    const toLabel = L(`unit.${to}`, config.units[to]?.label ?? to)

    // 结果摘要(纯文本) - 供 Copy 用
    const summary = useMemo(() => {
      if (!isFinite(result)) return LC('conversionNone', 'Conversion: —')
      return [
        LC('conversionSummary', 'Conversion Summary'),
        `  ${LC('summaryValue', 'Value:')} ${value} ${fromLabel}`,
        `  ${LC('summaryResult', 'Result:')} ${fmtNum(result, digits)} ${toLabel}`,
        `  ${LC('summaryFormula', 'Formula:')} ${fmtNum(toNum(value))} ${fromLabel} = ${fmtNum(result, digits)} ${toLabel}`,
      ].join('\n')
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [value, from, to, result, digits, fromLabel, toLabel, locale])

    // 导出内容(纯文本,人类可读;转换器输出简单,不必用 CSV)
    const downloadContent = useMemo(() => {
      if (!isFinite(result)) return summary
      const title = LC('conversionTitle', '{from} to {to} conversion')
        .replace('{from}', fromLabel)
        .replace('{to}', toLabel)
      return `${title}\n\n${fmtNum(toNum(value))} ${fromLabel} = ${fmtNum(result, digits)} ${toLabel}\n\n${LC('generatedBy', 'Generated by ToolHub')}`
      // eslint-disable-next-line react-hooks/exhaustive-deps
    }, [summary, value, from, to, result, digits, fromLabel, toLabel, locale])

    const downloadFilename = config.slug
      ? `${config.slug}-result.txt`
      : 'conversion-result.txt'

    return (
      <div className="space-y-6">
        {/* 输入区 + 右上角 Load Sample 按钮 */}
        <div className="flex flex-wrap items-center justify-between gap-3">
          <span className="text-sm font-semibold" style={{ color: 'rgb(var(--text-muted))' }}>{LC('convert', 'Convert')}</span>
          {sample && <LoadSampleButton onLoad={handleLoadSample} />}
        </div>
        <div className="grid grid-cols-1 gap-4 rounded-lg p-4 sm:grid-cols-3" style={{ backgroundColor: 'rgb(var(--bg-subtle))' }}>
          <CalculatorField
            id="value"
            label={LC('value', 'Value')}
            value={value}
            onChange={setValue}
            placeholder="1"
          />
          <div>
            <label htmlFor="from" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
              {LC('from', 'From')}
            </label>
            <select
              id="from"
              value={from}
              onChange={(e) => setFrom(e.target.value)}
              className="w-full rounded-lg border p-3 shadow-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-200" style={{ borderColor: 'rgb(var(--border-strong))', backgroundColor: 'rgb(var(--bg-card))', color: 'rgb(var(--text))' }}
            >
              {options.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </div>
          <div>
            <label htmlFor="to" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
              {LC('to', 'To')}
            </label>
            <select
              id="to"
              value={to}
              onChange={(e) => setTo(e.target.value)}
              className="w-full rounded-lg border p-3 shadow-sm outline-none focus:border-brand-500 focus:ring-2 focus:ring-brand-200" style={{ borderColor: 'rgb(var(--border-strong))', backgroundColor: 'rgb(var(--bg-card))', color: 'rgb(var(--text))' }}
            >
              {options.map((o) => (
                <option key={o.value} value={o.value}>
                  {o.label}
                </option>
              ))}
            </select>
          </div>
        </div>

        {/* 结果区(aria-live:换算结果变化时屏幕阅读器播报) */}
        <div role="status" aria-live="polite" className="grid grid-cols-1 gap-3 sm:grid-cols-2">
          <ResultCard
            label={LC('convertedValue', 'Converted value')}
            value={isFinite(result) ? `${fmtNum(result, digits)} ${toLabel}` : '—'}
            highlight
          />
          <ResultCard
            label={LC('formula', 'Formula')}
            value={
              isFinite(result)
                ? `${fmtNum(toNum(value))} ${fromLabel} = ${fmtNum(result, digits)} ${toLabel}`
                : '—'
            }
          />
        </div>

        {/* 结果操作行 - Copy 复制摘要,Download 下载结果 */}
        <ResultActions
          summary={summary}
          filename={downloadFilename}
          downloadContent={downloadContent}
        />

        {config.note && <CalculatorNote>{L('note', config.note)}</CalculatorNote>}
      </div>
    )
  }
}
