'use client'

import type { ReactNode } from 'react'
import type { Locale } from '@/lib/i18n'
import { useApp } from '@/components/providers/AppProviders'

// ──────────────────────────── en ────────────────────────────
const en: ReactNode = (
  <section className="prose-content mt-10 max-w-3xl">
    <h2>What Is This Tool?</h2>
    <p>
      This tool generates random numbers within any range you specify. Use it for picking
      lottery numbers, selecting contest winners, choosing a random student, running
      simulations, or any time you need an unbiased random selection.
    </p>
    <div>
      <h2>How It Works</h2>
      <p>
        This generator uses JavaScript&apos;s built-in pseudo-random number generator
        (PRNG), which produces numbers uniformly distributed across your chosen range. The
        &quot;unique numbers&quot; option ensures no repeats — useful for raffles and
        sampling without replacement.
      </p>
    </div>
    <div>
      <h2>True Random vs. Pseudo-Random</h2>
      <p>
        Most software (including this tool) uses <strong>pseudo-random</strong> numbers,
        generated by mathematical algorithms. These are sufficient for games, simulations,
        and everyday use, but predictable in principle. For cryptography or high-stakes
        lotteries, &quot;true&quot; random numbers from physical sources (radioactive decay,
        atmospheric noise) are needed — see Random.org for that.
      </p>
    </div>
    <div>
      <h2>Common Uses</h2>
      <ul>
        <li>Pick a contest or raffle winner fairly</li>
        <li>Generate lottery number combinations</li>
        <li>Randomize student or team selection</li>
        <li>Run Monte Carlo simulations</li>
        <li>Test code with random inputs</li>
        <li>Roll virtual dice (set min 1, max 6)</li>
      </ul>
    </div>
  </section>
)

// ──────────────────────────── 中文 ────────────────────────────
const zh: ReactNode = (
  <section className="prose-content mt-10 max-w-3xl">
    <h2>这是什么工具?</h2>
    <p>
      这个工具在你指定的任意范围内生成随机数。可用于抽取彩票号码、选出比赛获胜者、随机点名学生、运行模拟,或任何需要无偏随机选择的场景。
    </p>
    <div>
      <h2>工作原理</h2>
      <p>
        这个生成器使用 JavaScript 内置的伪随机数生成器(PRNG),生成的数字在你选择的范围内均匀分布。「不重复数字」选项确保不出现重复——适合抽奖和无放回抽样。
      </p>
    </div>
    <div>
      <h2>真随机 vs. 伪随机</h2>
      <p>
        大多数软件(包括本工具)使用<strong>伪随机</strong>数,由数学算法生成。对于游戏、模拟和日常使用已经足够,但原则上是可以预测的。对于密码学或高风险彩票,需要来自物理源(放射性衰变、大气噪声)的「真」随机数——这方面可以参考 Random.org。
      </p>
    </div>
    <div>
      <h2>常见用途</h2>
      <ul>
        <li>公平地选出比赛或抽奖获奖者</li>
        <li>生成彩票号码组合</li>
        <li>随机选择学生或团队</li>
        <li>运行 Monte Carlo 模拟</li>
        <li>用随机输入测试代码</li>
        <li>掷虚拟骰子(设最小值 1,最大值 6)</li>
      </ul>
    </div>
  </section>
)

// ──────────────────────────── Español ────────────────────────────
const es: ReactNode = (
  <section className="prose-content mt-10 max-w-3xl">
    <h2>¿Qué es esta herramienta?</h2>
    <p>
      Esta herramienta genera números aleatorios dentro de cualquier rango que especifiques.
      Úsala para elegir números de lotería, seleccionar ganadores de concursos, escoger un alumno
      al azar, ejecutar simulaciones o para cualquier selección aleatoria sin sesgo.
    </p>
    <div>
      <h2>Cómo funciona</h2>
      <p>
        Este generador usa el generador de números pseudoaleatorios (PRNG) integrado de
        JavaScript, que produce números distribuidos uniformemente en el rango elegido. La opción
        de «números únicos» garantiza que no haya repeticiones — útil para rifas y muestreo sin
        reemplazo.
      </p>
    </div>
    <div>
      <h2>Aleatorio real vs. pseudoaleatorio</h2>
      <p>
        La mayoría del software (incluida esta herramienta) usa números <strong>pseudoaleatorios</strong>,
        generados por algoritmos matemáticos. Son suficientes para juegos, simulaciones y uso
        cotidiano, pero predecibles en principio. Para criptografía o loterías de alto riesgo se
        necesitan números «verdaderamente» aleatorios de fuentes físicas (desintegración
        radiactiva, ruido atmosférico) — consulta Random.org para eso.
      </p>
    </div>
    <div>
      <h2>Usos comunes</h2>
      <ul>
        <li>Elegir un ganador de concurso o rifa de forma justa</li>
        <li>Generar combinaciones de números de lotería</li>
        <li>Aleatorizar la selección de alumnos o equipos</li>
        <li>Ejecutar simulaciones de Monte Carlo</li>
        <li>Probar código con entradas aleatorias</li>
        <li>Lanzar dados virtuales (mín. 1, máx. 6)</li>
      </ul>
    </div>
  </section>
)

// ──────────────────────────── Deutsch ────────────────────────────
const de: ReactNode = (
  <section className="prose-content mt-10 max-w-3xl">
    <h2>Was ist dieses Werkzeug?</h2>
    <p>
      Dieses Werkzeug erzeugt Zufallszahlen in einem beliebigen Bereich, den du festlegst. Nutze
      es für Lotteriezahlen, die Auswahl von Gewinnern, das zufällige Auswählen eines Schülers,
      Simulationen oder wann immer du eine unvoreingenommene Zufallsauswahl brauchst.
    </p>
    <div>
      <h2>Wie es funktioniert</h2>
      <p>
        Dieser Generator verwendet den integrierten Pseudozufallszahlengenerator (PRNG) von
        JavaScript, der gleichmäßig über deinen gewählten Bereich verteilte Zahlen erzeugt. Die
        Option „eindeutige Zahlen“ stellt sicher, dass keine Wiederholungen auftreten — nützlich
        für Verlosungen und Ziehen ohne Zurücklegen.
      </p>
    </div>
    <div>
      <h2>Echter Zufall vs. Pseudozufall</h2>
      <p>
        Die meiste Software (auch dieses Werkzeug) verwendet <strong>pseudozufällige</strong>
        Zahlen, die von mathematischen Algorithmen erzeugt werden. Sie reichen für Spiele,
        Simulationen und den Alltagsgebrauch aus, sind aber grundsätzlich vorhersagbar. Für
        Kryptografie oder hochdotierte Lotterien braucht man „echte“ Zufallszahlen aus
        physikalischen Quellen (radioaktiver Zerfall, atmosphärisches Rauschen) — siehe dazu
        Random.org.
      </p>
    </div>
    <div>
      <h2>Häufige Einsatzzwecke</h2>
      <ul>
        <li>Gerecht einen Gewinn für Wettbewerb oder Verlosung ziehen</li>
        <li>Loteriezahlen-Kombinationen erzeugen</li>
        <li>Schüler- oder Teamauswahl randomisieren</li>
        <li>Monte-Carlo-Simulationen durchführen</li>
        <li>Code mit zufälligen Eingaben testen</li>
        <li>Virtuelle Würfel werfen (Min. 1, Max. 6)</li>
      </ul>
    </div>
  </section>
)

const CONTENT_BY_LOCALE: Record<Locale, ReactNode> = { en, zh, es, de }

export function RandomNumberGeneratorContent(): ReactNode {
  const { locale } = useApp()
  return CONTENT_BY_LOCALE[locale] ?? en
}
