'use client'

import { useState, useMemo } from 'react'
import { CopyButton } from '@/components/CopyButton'
import { ResultActions } from '@/components/ResultActions'
import { useApp } from '@/components/providers/AppProviders'
import { tui } from '@/lib/i18n/tool-l10n'

/**
 * Nginx Config Generator —— 反向代理配置生成器
 *
 * 表单驱动实时生成完整 nginx server block:SSL(Let's Encrypt 证书路径 + HTTP→HTTPS 跳转)、
 * WebSocket upgrade map、gzip、静态资源缓存、client_max_body_size。
 * 始终带上 Host/X-Real-IP/X-Forwarded-For/X-Forwarded-Proto 与 proxy_http_version 1.1。
 */

interface NginxOptions {
  domain: string
  target: string
  ssl: boolean
  port: string
  websocket: boolean
  gzip: boolean
  staticCache: boolean
  maxBody: string
}

/** 域名校验:localhost、通配符 *.example.com、或多标签域名(TLD ≥ 2 字母) */
const DOMAIN_RE = /^(?:[a-zA-Z0-9](?:[a-zA-Z0-9-]*[a-zA-Z0-9])?\.)+[a-zA-Z]{2,63}$/
function isValidDomain(d: string): boolean {
  const v = d.trim()
  if (v === 'localhost') return true
  return DOMAIN_RE.test(v.startsWith('*.') ? v.slice(2) : v)
}

/** proxy target 校验:必须是 http/https 绝对 URL */
function isValidTarget(t: string): boolean {
  try {
    const u = new URL(t.trim())
    return u.protocol === 'http:' || u.protocol === 'https:'
  } catch {
    return false
  }
}

/** target 是否带路径(如 http://host:3000/app)——nginx 在正则 location 内不接受 proxy_pass 带 URI 部分 */
function targetHasPath(t: string): boolean {
  try {
    const u = new URL(t.trim())
    return u.pathname !== '/' && u.pathname !== ''
  } catch {
    return false
  }
}

function buildNginxConfig(o: NginxOptions): string {
  // 自由文本拼进多行产物前剥离换行(清洗输入防注入多余 directive 行)
  const domain = o.domain.replace(/[\r\n]+/g, ' ').trim() || 'example.com'
  const target = o.target.replace(/[\r\n]+/g, ' ').trim() || 'http://127.0.0.1:3000'
  const port = o.port.replace(/[\r\n]+/g, ' ').trim() || '80'
  const lines: string[] = []

  lines.push(`# Nginx reverse proxy configuration for ${domain}`)
  lines.push('# Generated by ToolHub Nginx Config Generator')
  lines.push(`# Install: save this file to /etc/nginx/sites-available/${domain}.conf, then:`)
  lines.push(`#   sudo ln -s /etc/nginx/sites-available/${domain}.conf /etc/nginx/sites-enabled/`)
  lines.push('#   sudo nginx -t && sudo systemctl reload nginx')
  lines.push('')

  if (o.websocket) {
    lines.push('# Map the Connection header for WebSocket upgrades')
    lines.push('map $http_upgrade $connection_upgrade {')
    lines.push('    default upgrade;')
    lines.push("    ''      close;")
    lines.push('}')
    lines.push('')
  }

  if (o.ssl) {
    lines.push('# Redirect all plain HTTP traffic to HTTPS')
    lines.push('server {')
    lines.push('    listen 80;')
    lines.push(`    server_name ${domain};`)
    lines.push('    return 301 https://$host$request_uri;')
    lines.push('}')
    lines.push('')
  }

  lines.push('server {')
  if (o.ssl) {
    lines.push('    listen 443 ssl;')
    lines.push('    http2 on;')
  } else {
    lines.push(`    listen ${port};`)
  }
  lines.push(`    server_name ${domain};`)
  lines.push('')

  if (o.ssl) {
    lines.push("    # Let's Encrypt certificate (certbot)")
    lines.push(`    ssl_certificate     /etc/letsencrypt/live/${domain}/fullchain.pem;`)
    lines.push(`    ssl_certificate_key /etc/letsencrypt/live/${domain}/privkey.pem;`)
    lines.push('')
  }

  lines.push('    # Maximum request body size (uploads)')
  lines.push(`    client_max_body_size ${o.maxBody};`)
  lines.push('')

  if (o.gzip) {
    lines.push('    # Gzip compression for text-based responses')
    lines.push('    gzip on;')
    lines.push('    gzip_vary on;')
    lines.push('    gzip_proxied any;')
    lines.push('    gzip_comp_level 6;')
    lines.push('    gzip_min_length 1024;')
    lines.push(
      '    gzip_types text/plain text/css application/json application/javascript application/x-javascript text/xml application/xml application/xml+rss text/javascript image/svg+xml;',
    )
    lines.push('')
  }

  if (o.staticCache) {
    lines.push('    # Cache static assets in the browser for 30 days')
    lines.push('    location ~* \\.(?:js|css|png|jpg|jpeg|gif|ico|svg|webp|woff2?)$ {')
    lines.push(`        proxy_pass ${target};`)
    lines.push('        proxy_set_header Host $host;')
    lines.push('        expires 30d;')
    lines.push('        add_header Cache-Control "public, immutable";')
    lines.push('        access_log off;')
    lines.push('    }')
    lines.push('')
  }

  lines.push('    # Reverse proxy to the application server')
  lines.push('    location / {')
  lines.push(`        proxy_pass ${target};`)
  lines.push('        proxy_http_version 1.1;')
  lines.push('')
  lines.push('        # Forward the original client information')
  lines.push('        proxy_set_header Host $host;')
  lines.push('        proxy_set_header X-Real-IP $remote_addr;')
  lines.push('        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;')
  lines.push('        proxy_set_header X-Forwarded-Proto $scheme;')

  if (o.websocket) {
    lines.push('')
    lines.push('        # WebSocket support')
    lines.push('        proxy_set_header Upgrade $http_upgrade;')
    lines.push('        proxy_set_header Connection $connection_upgrade;')
  }

  lines.push('    }')
  lines.push('}')
  lines.push('')
  return lines.join('\n')
}

function Toggle({
  checked,
  onChange,
  label,
}: {
  checked: boolean
  onChange: (v: boolean) => void
  label: string
}) {
  return (
    <label
      className="flex cursor-pointer items-center gap-2 rounded-lg border p-3 text-sm transition"
      style={{ borderColor: 'rgb(var(--border))', color: 'rgb(var(--text))' }}
    >
      <input
        type="checkbox"
        checked={checked}
        onChange={(e) => onChange(e.target.checked)}
        className="h-4 w-4 accent-brand-600"
      />
      {label}
    </label>
  )
}

export function NginxConfigGeneratorClient() {
  const { locale } = useApp()
  // 取本地化 UI 串;缺失回退英文(SSR 恒英文)。
  const L = (key: string, fb: string) => tui('nginx-config-generator', locale, key, fb)

  const [domain, setDomain] = useState('example.com')
  const [target, setTarget] = useState('http://127.0.0.1:3000')
  const [ssl, setSsl] = useState(true)
  const [port, setPort] = useState('80')
  const [websocket, setWebsocket] = useState(false)
  const [gzip, setGzip] = useState(true)
  const [staticCache, setStaticCache] = useState(false)
  const [maxBody, setMaxBody] = useState('10m')

  const config = useMemo(
    () => buildNginxConfig({ domain, target, ssl, port, websocket, gzip, staticCache, maxBody }),
    [domain, target, ssl, port, websocket, gzip, staticCache, maxBody],
  )

  const fileDomain = domain.trim().replace(/[^a-zA-Z0-9.-]/g, '') || 'nginx'

  // 输入校验(空值回退默认值,不算非法)
  const domainInvalid = domain.trim() !== '' && !isValidDomain(domain)
  const targetInvalid = target.trim() !== '' && !isValidTarget(target)
  // target 带路径 → 正则 location 内 proxy_pass 带 URI,nginx -t 会报错
  const warnPath = targetHasPath(target)

  const inputClass =
    'w-full rounded-lg border p-4 font-mono text-sm shadow-sm outline-none transition focus:ring-2'
  const inputStyle = {
    borderColor: 'rgb(var(--border-strong))',
    backgroundColor: 'rgb(var(--bg-card))',
    color: 'rgb(var(--text))',
  } as const

  return (
    <div className="space-y-5">
      {/* 表单 */}
      <div className="grid gap-4 sm:grid-cols-2">
        <div>
          <label htmlFor="nginx-domain" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
            {L('serverNameLabel', 'Server name (domain)')}
          </label>
          <input
            id="nginx-domain"
            type="text"
            value={domain}
            onChange={(e) => setDomain(e.target.value)}
            placeholder="example.com"
            spellCheck={false}
            className={inputClass}
            style={domainInvalid ? { ...inputStyle, borderColor: '#ef4444' } : inputStyle}
          />
          {domainInvalid && (
            <p className="mt-1.5 text-xs text-red-500 dark:text-red-400">
              {L('errDomainInvalid', 'Enter a valid domain (e.g. example.com or *.example.com).')}
            </p>
          )}
        </div>
        <div>
          <label htmlFor="nginx-target" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
            {L('proxyTargetLabel', 'Proxy target')}
          </label>
          <input
            id="nginx-target"
            type="text"
            value={target}
            onChange={(e) => setTarget(e.target.value)}
            placeholder="http://127.0.0.1:3000"
            spellCheck={false}
            className={inputClass}
            style={targetInvalid ? { ...inputStyle, borderColor: '#ef4444' } : inputStyle}
          />
          {targetInvalid && (
            <p className="mt-1.5 text-xs text-red-500 dark:text-red-400">
              {L('errTargetInvalid', 'Enter a valid http:// or https:// URL (e.g. http://127.0.0.1:3000).')}
            </p>
          )}
        </div>
        {!ssl && (
          <div>
            <label htmlFor="nginx-port" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
              {L('listenPortLabel', 'Listen port')}
            </label>
            <input
              id="nginx-port"
              type="text"
              value={port}
              onChange={(e) => setPort(e.target.value)}
              placeholder="80"
              spellCheck={false}
              className={inputClass}
              style={inputStyle}
            />
          </div>
        )}
        <div>
          <label htmlFor="nginx-maxbody" className="mb-1.5 block text-sm font-medium" style={{ color: 'rgb(var(--text-muted))' }}>
            client_max_body_size
          </label>
          <select
            id="nginx-maxbody"
            value={maxBody}
            onChange={(e) => setMaxBody(e.target.value)}
            className={inputClass}
            style={inputStyle}
          >
            <option value="1m">1m</option>
            <option value="10m">10m</option>
            <option value="50m">50m</option>
            <option value="100m">100m</option>
          </select>
        </div>
      </div>

      {/* 开关 */}
      <div className="grid grid-cols-1 gap-3 sm:grid-cols-2">
        <Toggle checked={ssl} onChange={setSsl} label={L('enableSsl', 'Enable SSL (HTTPS + HTTP redirect)')} />
        <Toggle checked={websocket} onChange={setWebsocket} label={L('websocketSupport', 'WebSocket support')} />
        <Toggle checked={gzip} onChange={setGzip} label={L('gzipCompression', 'Gzip compression')} />
        <Toggle checked={staticCache} onChange={setStaticCache} label={L('staticAssetsCaching', 'Static assets caching (30d)')} />
      </div>

      {/* 输出 */}
      <div className="space-y-3">
        <div className="flex items-center justify-between">
          <span className="text-sm font-semibold" style={{ color: 'rgb(var(--text))' }}>
            {L('generatedConfig', 'Generated config')}
          </span>
          <CopyButton value={config} label={L('copy', 'Copy')} />
        </div>
        {warnPath && (
          <div className="rounded-lg border border-amber-200 bg-amber-50 p-3 text-xs text-amber-700 dark:border-amber-800 dark:bg-amber-950/40 dark:text-amber-300">
            ⚠️{' '}
            {L(
              'warnTargetPath',
              'The proxy target contains a path ({path}). nginx does not accept a URI part in proxy_pass inside a regex location, so nginx -t will fail with "proxy_pass cannot have URI part". Remove the path (e.g. http://host:3000), or use an upstream block with rewrite.',
            ).replace('{path}', target.trim())}
          </div>
        )}
        <pre
          className="w-full overflow-x-auto rounded-lg border p-4 font-mono text-sm shadow-sm"
          style={{
            borderColor: 'rgb(var(--border-strong))',
            backgroundColor: 'rgb(var(--bg-card))',
            color: 'rgb(var(--text))',
          }}
        >
          <code>{config}</code>
        </pre>
        <ResultActions
          summary={config}
          filename={`${fileDomain}.conf`}
          downloadContent={config}
        />
      </div>

      <p
        className="rounded-md p-3 text-xs"
        style={{ backgroundColor: 'rgb(var(--bg-subtle))', color: 'rgb(var(--text-subtle))' }}
      >
        {L('notePlace', '📁 Place the file in')} <code>/etc/nginx/sites-available/</code> {L('noteSymlink', 'and symlink it into')}{' '}
        <code>/etc/nginx/sites-enabled/</code>{L('noteThenRun', ', then run')} <code>sudo nginx -t &amp;&amp; sudo systemctl reload nginx</code>.{' '}
        {L('noteClientSide', '🔒 Generated 100% client-side — nothing is sent anywhere.')}
      </p>
    </div>
  )
}
